import { useEffect,useMemo,useState } from 'react';
const BASE=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'');const TOKEN='roviq_parts_token';
type CoreCase={id:string;case_type:string;state:string;priority:string;version:number;pending_approvals:number;active_workflows:number};
type Approval={id:string;action:string;state:string;approval_type:string};
type Action={to:string;action:string;approvalRecommended:boolean};type Actions={version:number;transitions:Action[]};
async function req<T>(path:string,init:RequestInit={}):Promise<T>{const t=localStorage.getItem(TOKEN);const r=await fetch(`${BASE}${path}`,{...init,headers:{'content-type':'application/json',...(t?{authorization:`Bearer ${t}`}:{}),...(init.headers??{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error??`request_failed_${r.status}`)}return r.json()}
const human=(v:string)=>v.replaceAll('_',' ');
export function CoreCasePanel(){const[cases,setCases]=useState<CoreCase[]>([]),[selected,setSelected]=useState<string|null>(null),[actions,setActions]=useState<Actions|null>(null),[approvals,setApprovals]=useState<Approval[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[refresh,setRefresh]=useState(0);
useEffect(()=>{let live=true;(async()=>{try{setError('');const r=await req<{cases:CoreCase[]}>('/api/core/me/cases');if(!live)return;setCases(r.cases);setSelected(cur=>cur&&r.cases.some(c=>c.id===cur)?cur:r.cases[0]?.id??null)}catch(e){if(live)setError(e instanceof Error?e.message:'Unable to load Core cases')}})();return()=>{live=false}},[refresh]);
useEffect(()=>{if(!selected){setActions(null);setApprovals([]);return}let live=true;Promise.all([req<Actions>(`/api/core/cases/${selected}/actions`),req<{approvals:Approval[]}>(`/api/core/cases/${selected}/approvals`)]).then(([a,p])=>{if(live){setActions(a);setApprovals(p.approvals)}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'Unable to load Core case actions')});return()=>{live=false}},[selected,refresh]);
const c=cases.find(x=>x.id===selected)??null;const approved=useMemo(()=>new Map(approvals.filter(a=>a.state==='approved').map(a=>[a.action,a])),[approvals]);
async function move(a:Action){if(!selected||!actions)return;setBusy(a.to);try{setError('');const approval=approved.get(a.action);await req(`/api/core/cases/${selected}/transition`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({expectedVersion:actions.version,requestedTransition:a.to,approvalId:approval?.id,evidence:{source:'parts_core_workspace'}})});setRefresh(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Unable to update Core case')}finally{setBusy('')}}
return <section className="panel inventory-panel"><div className="actions" style={{justifyContent:'space-between'}}><div><span className="eyebrow">ROVIQ Core</span><h2>Assigned coordinated cases</h2><p>Case state remains authoritative while parts fulfilment continues in the order workflow above.</p></div><button className="secondary" type="button" onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div>{error&&<div className="error">{human(error)}</div>}<div className="grid">{cases.map(x=><article key={x.id} className={`card order-card ${selected===x.id?'active':''}`}><button type="button" className="order-select" onClick={()=>setSelected(x.id)}><span className="pill">{human(x.state)}</span><h3>{human(x.case_type)} {x.id.slice(0,8)}</h3><p>{x.active_workflows} workflow(s) · {x.pending_approvals} approval(s)</p></button></article>)}</div>{c&&<div className="panel spatial"><span className="eyebrow">Selected Core case</span><h2>Case {c.id.slice(0,8)}</h2><p>State {human(c.state)} · priority {human(c.priority)} · v{c.version}</p><div className="actions">{actions?.transitions.map(a=>{const ok=!a.approvalRecommended||approved.has(a.action);return <button key={a.to} className="secondary" type="button" disabled={Boolean(busy)||!ok} onClick={()=>void move(a)}>{busy===a.to?'Applying…':human(a.to)}{!ok?' · approval':''}</button>})}</div></div>}</section>}
