import type { PoolClient } from 'pg';
import { pool } from '../db/pool.js';
import type { Principal } from '../types/principal.js';
import { appendCaseEvent } from './orchestration.js';
import { audit, validIdentityId } from './audit.js';

const ZERO_DECIMAL_CURRENCIES=new Set(['BIF','CLP','DJF','GNF','JPY','KMF','KRW','MGA','PYG','RWF','UGX','VND','VUV','XAF','XOF','XPF']);
const THREE_DECIMAL_CURRENCIES=new Set(['BHD','JOD','KWD','OMR','TND']);
function amountEquals(a:unknown,b:unknown){return Number(a)===Number(b);}
function normalizeProvider(provider:unknown){const normalized=String(provider??'manual').trim().toLowerCase();return normalized||'manual';}
function normalizeFinancialCurrency(currency:string|undefined){const normalized=(currency??'USD').toUpperCase();if(THREE_DECIMAL_CURRENCIES.has(normalized)) throw new Error('currency_precision_unsupported');return normalized;}
function assertFinancialAmount(amount:number,currency:string){if(!Number.isFinite(amount)||amount<0) throw new Error('invalid_financial_amount');const factor=ZERO_DECIMAL_CURRENCIES.has(currency)?1:100;const rounded=Math.round(amount*factor)/factor;if(!Number.isSafeInteger(Math.round(amount*factor))||rounded!==amount) throw new Error('invalid_financial_amount');}
async function assertFinancialCaseAccess(principal:Principal,caseId:string,client:Pick<PoolClient,'query'>){
  if(principal.role!=='admin') throw new Error('forbidden');
  if(!principal.actorId)return;
  const actor=await client.query(`select organization_id from actors where id=$1 and status='active'`,[principal.actorId]);if(!actor.rowCount) throw new Error('forbidden');
  const organizationId=actor.rows[0].organization_id;
  const scoped=await client.query(`select exists(select 1 from service_cases sc left join actors owner on owner.id=sc.current_owner_actor_id left join actors selected on selected.id=sc.selected_actor_id where sc.id=$1 and (owner.organization_id=$2 or selected.organization_id=$2 or exists(select 1 from matches_offers mo join actors a on a.id=mo.actor_id where mo.case_id=sc.id and mo.outcome='accepted' and a.organization_id=$2) or exists(select 1 from transport_dispatches td join actors a on a.id=td.provider_actor_id where td.case_id=sc.id and a.organization_id=$2) or exists(select 1 from parts_orders po join actors a on a.id=po.supplier_actor_id where po.case_id=sc.id and a.organization_id=$2) or exists(select 1 from mobility_allocations ma join actors a on a.id=ma.provider_actor_id where ma.case_id=sc.id and a.organization_id=$2))) as allowed`,[caseId,organizationId]);
  if(!scoped.rows[0]?.allowed) throw new Error('forbidden');
}
async function insertFinancialAudit(client:Pick<PoolClient,'query'>,principal:Principal,action:string,objectType:string,objectId:string,ruleBasis:string,metadata:unknown={}){await client.query(`insert into audit_log(principal_role,principal_actor_id,principal_identity_id,action,object_type,object_id,rule_basis,metadata) values($1,$2,$3,$4,$5,$6,$7,$8)`,[principal.role,principal.actorId??null,validIdentityId(principal.identityId),action,objectType,objectId,ruleBasis,JSON.stringify(metadata)]);}

export async function createPaymentIntent(principal:Principal,input:{caseId:string;amount:number;currency?:string;description?:string;provider?:string;providerIntentId?:string;clientRequestId?:string;metadata?:Record<string,unknown>}){
  const normalizedCurrency=normalizeFinancialCurrency(input.currency),normalizedProvider=normalizeProvider(input.provider);assertFinancialAmount(input.amount,normalizedCurrency);const client=await pool.connect();
  try{await client.query('begin');const c=await client.query('select * from service_cases where id=$1 for update',[input.caseId]);if(!c.rowCount) throw new Error('case_not_found');await assertFinancialCaseAccess(principal,input.caseId,client);const customerActorId=c.rows[0].customer_actor_id??null;const plan=await client.query('select id,current_revision from service_plans where case_id=$1',[input.caseId]);if(plan.rowCount){const approval=await client.query(`select state from case_approvals where case_id=$1 and service_plan_id=$2 and revision=$3 and approval_type='quote' order by created_at desc limit 1`,[input.caseId,plan.rows[0].id,plan.rows[0].current_revision]);if(!approval.rowCount||approval.rows[0].state!=='approved') throw new Error('quote_not_approved');}
    if(input.clientRequestId){
      const existingRequest=await client.query(
        `select * from payment_intents where provider=$1 and client_request_id=$2`,
        [normalizedProvider,input.clientRequestId]
      );
      if(existingRequest.rowCount){
        const row=existingRequest.rows[0];
        if(row.case_id!==input.caseId||!amountEquals(row.amount,input.amount)||row.currency!==normalizedCurrency) throw new Error('payment_request_conflict');
        await client.query('commit');
        return row;
      }
    }
    if(input.providerIntentId){const existing=await client.query(`select * from payment_intents where provider=$1 and provider_intent_id=$2`,[normalizedProvider,input.providerIntentId]);if(existing.rowCount){const row=existing.rows[0];if(row.case_id!==input.caseId||!amountEquals(row.amount,input.amount)||row.currency!==normalizedCurrency) throw new Error('provider_intent_conflict');await client.query('commit');return row;}}
    const r=await client.query(`insert into payment_intents(case_id,customer_actor_id,provider,provider_intent_id,client_request_id,amount,currency,description,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[input.caseId,customerActorId,normalizedProvider,input.providerIntentId??null,input.clientRequestId??null,input.amount,normalizedCurrency,input.description??null,JSON.stringify(input.metadata??{})]);const p=r.rows[0];await appendCaseEvent(input.caseId,'PAYMENT_INTENT_CREATED',principal,{paymentIntentId:p.id,amount:p.amount,currency:p.currency},client);await insertFinancialAudit(client,principal,'create_payment_intent','payment_intent',p.id,'case_payment',{caseId:input.caseId,amount:input.amount});await client.query('commit');return p;
  }catch(error){await client.query('rollback');throw error;}finally{client.release();}
}

export async function refundPayment(principal:Principal,paymentIntentId:string,amount:number,providerEventId?:string,payload:Record<string,unknown>={}){
  const client=await pool.connect();try{await client.query('begin');const current=await client.query('select * from payment_intents where id=$1 for update',[paymentIntentId]);if(!current.rowCount) throw new Error('payment_not_found');const p=current.rows[0],eventProvider=normalizeProvider(p.provider);assertFinancialAmount(amount,String(p.currency).toUpperCase());if(amount===0) throw new Error('invalid_refund_amount');await assertFinancialCaseAccess(principal,p.case_id,client);
    if(providerEventId){const prior=await client.query(`select payment_intent_id,event_type,amount from payment_events where provider=$1 and provider_event_id=$2`,[eventProvider,providerEventId]);if(prior.rowCount){const event=prior.rows[0];if(event.payment_intent_id!==paymentIntentId||event.event_type!=='REFUND'||!amountEquals(event.amount,amount)) throw new Error('provider_event_conflict');await client.query('commit');return p;}}
    if(!['captured','partially_refunded'].includes(p.state)) throw new Error('refund_not_allowed');const refunded=await client.query(`select coalesce(sum(amount),0)::numeric as amount from payment_events where payment_intent_id=$1 and event_type='REFUND'`,[paymentIntentId]);const totalRefunded=Number(refunded.rows[0].amount)+amount;if(totalRefunded>Number(p.amount)) throw new Error('invalid_refund_amount');const committedPayouts=await client.query(`select coalesce(sum(amount),0)::numeric as amount from settlement_payouts where payment_intent_id=$1 and state not in ('cancelled','failed')`,[paymentIntentId]);if(totalRefunded+Number(committedPayouts.rows[0].amount)>Number(p.amount)) throw new Error('refund_exceeds_available_balance');const nextState=totalRefunded===Number(p.amount)?'refunded':'partially_refunded';const updated=await client.query('update payment_intents set state=$1,updated_at=now() where id=$2 returning *',[nextState,paymentIntentId]);await client.query(`insert into payment_events(payment_intent_id,event_type,amount,provider,provider_event_id,payload) values($1,'REFUND',$2,$3,$4,$5)`,[paymentIntentId,amount,eventProvider,providerEventId??null,JSON.stringify(payload)]);await client.query(`insert into ledger_entries(case_id,payment_intent_id,entry_type,account_code,amount,currency,state,external_reference,metadata) values($1,$2,'refund','customer_refund',$3,$4,'posted',$5,$6)`,[p.case_id,paymentIntentId,-Math.abs(amount),p.currency,providerEventId??null,JSON.stringify({provider:eventProvider})]);await appendCaseEvent(p.case_id,'PAYMENT_REFUNDED',principal,{paymentIntentId,amount,state:nextState},client);await client.query('commit');await audit(principal,'refund_payment','payment_intent',paymentIntentId,'refund',{amount});return updated.rows[0];
  }catch(error){await client.query('rollback');throw error;}finally{client.release();}
}

export async function createPayout(principal:Principal,input:{caseId:string;counterpartyActorId:string;paymentIntentId?:string;amount:number;currency?:string;provider?:string;providerPayoutId?:string;metadata?:Record<string,unknown>}){
  const normalizedCurrency=normalizeFinancialCurrency(input.currency),normalizedProvider=normalizeProvider(input.provider);assertFinancialAmount(input.amount,normalizedCurrency);const client=await pool.connect();try{await client.query('begin');const serviceCase=await client.query('select id from service_cases where id=$1 for update',[input.caseId]);if(!serviceCase.rowCount) throw new Error('case_not_found');await assertFinancialCaseAccess(principal,input.caseId,client);const actor=await client.query(`select id,status from actors where id=$1`,[input.counterpartyActorId]);if(!actor.rowCount||actor.rows[0].status!=='active') throw new Error('payout_counterparty_invalid');const requestedPaymentIntentId=input.paymentIntentId??null;let linkedPaymentAmount:number|null=null;
    if(input.paymentIntentId){const payment=await client.query(`select case_id,currency,amount from payment_intents where id=$1 for update`,[input.paymentIntentId]);if(!payment.rowCount) throw new Error('payment_not_found');if(payment.rows[0].case_id!==input.caseId) throw new Error('payout_payment_case_mismatch');if(payment.rows[0].currency!==normalizedCurrency) throw new Error('payout_currency_mismatch');linkedPaymentAmount=Number(payment.rows[0].amount);}
    if(input.providerPayoutId){const existing=await client.query(`select * from settlement_payouts where provider=$1 and provider_payout_id=$2`,[normalizedProvider,input.providerPayoutId]);if(existing.rowCount){const row=existing.rows[0];if(row.case_id!==input.caseId||row.counterparty_actor_id!==input.counterpartyActorId||!amountEquals(row.amount,input.amount)||row.currency!==normalizedCurrency||(row.payment_intent_id??null)!==requestedPaymentIntentId) throw new Error('provider_payout_conflict');await client.query('commit');return row;}}
    if(input.paymentIntentId&&linkedPaymentAmount!==null){const committed=await client.query(`select coalesce((select sum(amount) from payment_events where payment_intent_id=$1 and event_type='REFUND'),0)::numeric as refunded,coalesce((select sum(amount) from settlement_payouts where payment_intent_id=$1 and state not in ('cancelled','failed')),0)::numeric as paid_out`,[input.paymentIntentId]);const available=linkedPaymentAmount-Number(committed.rows[0].refunded)-Number(committed.rows[0].paid_out);if(input.amount>available) throw new Error('payout_exceeds_available_balance');}
    const r=await client.query(`insert into settlement_payouts(case_id,counterparty_actor_id,payment_intent_id,amount,currency,provider,provider_payout_id,metadata) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[input.caseId,input.counterpartyActorId,requestedPaymentIntentId,input.amount,normalizedCurrency,normalizedProvider,input.providerPayoutId??null,JSON.stringify(input.metadata??{})]);const payout=r.rows[0];await appendCaseEvent(input.caseId,'PAYOUT_CREATED',principal,{payoutId:payout.id,counterpartyActorId:input.counterpartyActorId,amount:input.amount},client);await insertFinancialAudit(client,principal,'create_payout','settlement_payout',payout.id,'provider_settlement',{caseId:input.caseId});await client.query('commit');return payout;
  }catch(error){await client.query('rollback');throw error;}finally{client.release();}
}

export async function updatePayoutState(principal:Principal,payoutId:string,nextState:'approved'|'processing'|'paid'|'failed'|'cancelled',externalReference?:string){
  const client=await pool.connect();try{await client.query('begin');const current=await client.query('select * from settlement_payouts where id=$1 for update',[payoutId]);if(!current.rowCount) throw new Error('payout_not_found');const p=current.rows[0];await assertFinancialCaseAccess(principal,p.case_id,client);let canonicalReference=p.provider_payout_id??null;if(nextState==='paid'&&externalReference){const suppliedReference=externalReference.trim();if(!suppliedReference) throw new Error('payout_provider_reference_required');if(canonicalReference&&canonicalReference!==suppliedReference) throw new Error('provider_payout_conflict');canonicalReference=suppliedReference;}if(nextState==='paid'&&normalizeProvider(p.provider)!=='manual'&&!canonicalReference) throw new Error('payout_provider_reference_required');if(p.state===nextState){if(nextState==='paid'&&canonicalReference!==p.provider_payout_id){try{const repaired=await client.query(`update settlement_payouts set provider_payout_id=$1,updated_at=now() where id=$2 returning *`,[canonicalReference,payoutId]);await client.query('commit');return repaired.rows[0];}catch(error){if((error as {code?:string})?.code==='23505') throw new Error('provider_payout_conflict');throw error;}}await client.query('commit');return p;}
    const allowed:Record<string,string[]>={pending:['approved','cancelled'],approved:['processing','paid','cancelled'],processing:['paid','failed'],paid:[],failed:['processing','cancelled'],cancelled:[]};if(!allowed[p.state]?.includes(nextState)) throw new Error('invalid_payout_transition');if(nextState==='paid'&&p.payment_intent_id){const payment=await client.query(`select state from payment_intents where id=$1 for update`,[p.payment_intent_id]);if(!payment.rowCount) throw new Error('payment_not_found');if(!['captured','partially_refunded'].includes(payment.rows[0].state)) throw new Error('payout_payment_not_funded');}let r;try{r=await client.query(`update settlement_payouts set state=$1,provider_payout_id=$2,paid_at=case when $1='paid' then now() else paid_at end,updated_at=now() where id=$3 returning *`,[nextState,canonicalReference,payoutId]);}catch(error){if((error as {code?:string})?.code==='23505') throw new Error('provider_payout_conflict');throw error;}if(nextState==='paid')await client.query(`insert into ledger_entries(case_id,payment_intent_id,payout_id,entry_type,account_code,counterparty_actor_id,amount,currency,state,external_reference,metadata) values($1,$2,$3,'provider_payout','provider_payable',$4,$5,$6,'posted',$7,$8)`,[p.case_id,p.payment_intent_id??null,payoutId,p.counterparty_actor_id,-Math.abs(Number(p.amount)),p.currency,canonicalReference,JSON.stringify({provider:normalizeProvider(p.provider)})]);await appendCaseEvent(p.case_id,`PAYOUT_${nextState.toUpperCase()}`,principal,{payoutId,counterpartyActorId:p.counterparty_actor_id,amount:p.amount},client);await client.query('commit');await audit(principal,'payout_state_change','settlement_payout',payoutId,`${p.state}->${nextState}`);return r.rows[0];
  }catch(error){await client.query('rollback');throw error;}finally{client.release();}
}
