import{useEffect,useState,type FormEvent}from'react';import{LocalMap}from'./LocalMap';
type Principal={role:string;actorId?:string};type Dispatch={id:string;case_id:string;transport_type:string;status:string;pickup_location?:unknown;dropoff_location?:unknown;eta_at?:string};type MapMode='day'|'night';
const BASE=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'');const TOKEN='roviq_tow_token',PRINCIPAL='roviq_tow_principal',MODE='roviq_tow_mode';
async function req<T>(path:string,init:RequestInit={}):Promise<T>{const t=localStorage.getItem(TOKEN);const r=await fetch(`${BASE}${path}`,{...init,headers:{'content-type':'application/json',...(t?{authorization:`Bearer ${t}`}:{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error??`request_failed_${r.status}`)}return r.json()}
const next:Record<string,string>={accepted:'en_route',en_route:'arrived',arrived:'vehicle_loaded',vehicle_loaded:'in_transit',in_transit:'delivered'};
const stageLabel:Record<string,string>={assigned:'Assignment',accepted:'Accepted',en_route:'En route',arrived:'Arrived',vehicle_loaded:'Vehicle loaded',in_transit:'In transit',delivered:'Delivered',declined:'Declined'};
function initialMode():MapMode{const saved=localStorage.getItem(MODE);if(saved==='day'||saved==='night')return saved;const h=new Date().getHours();return h>=7&&h<19?'day':'night'}
export default function App(){const[p,setP]=useState<Principal|null>(()=>{try{return JSON.parse(localStorage.getItem(PRINCIPAL)??'null')}catch{return null}}),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[items,setItems]=useState<Dispatch[]>([]),[selected,setSelected]=useState<string|null>(null),[mode,setMode]=useState<MapMode>(initialMode);
useEffect(()=>{document.documentElement.dataset.roviqMode=mode;localStorage.setItem(MODE,mode)},[mode]);
async function login(e:FormEvent){e.preventDefault();try{setError('');const r=await req<{accessToken:string;principal:Principal}>('/api/auth/login',{method:'POST',body:JSON.stringify({email:email.trim(),password})});let session=r;if(r.principal.role==='admin'){localStorage.setItem(TOKEN,r.accessToken);session=await req<{accessToken:string;principal:Principal}>('/api/admin/testing/tow-session',{method:'POST',body:'{}'})}if(session.principal.role!=='tow'||!session.principal.actorId)throw new Error('This portal requires a tow/valet account.');localStorage.setItem(TOKEN,session.accessToken);localStorage.setItem(PRINCIPAL,JSON.stringify(session.principal));setP(session.principal)}catch(e){localStorage.removeItem(TOKEN);localStorage.removeItem(PRINCIPAL);setError(e instanceof Error?e.message:'Unable to sign in')}}
async function load(){try{setError('');const r=await req<{dispatches:Dispatch[]}>('/api/transport/me/dispatches');setItems(r.dispatches);if(!selected&&r.dispatches[0])setSelected(r.dispatches[0].id)}catch(e){setError(e instanceof Error?e.message:'Unable to load dispatches')}}useEffect(()=>{if(p)void load()},[p]);
async function setStatus(d:Dispatch,status:string){try{setError('');await req(`/api/transport/${d.id}/status`,{method:'POST',body:JSON.stringify({status})});if(status==='delivered'){const available=await req<{transitions:{toState:string}[]}>(`/api/maintenance/cases/${d.case_id}/transitions`);if(available.transitions.some(t=>t.toState==='provider_selection'))await req(`/api/maintenance/cases/${d.case_id}/transition`,{method:'POST',body:JSON.stringify({toState:'provider_selection',metadata:{source:'tow_portal',transportDispatchId:d.id}})})}await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}}function logout(){localStorage.removeItem(TOKEN);localStorage.removeItem(PRINCIPAL);setP(null)}
if(!p)return <Login {...{email,setEmail,password,setPassword,show,setShow,error,login}}/>;
const active=items.find(d=>d.id===selected)??items[0]??null;const scroll=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});
return <div className="shell"><style>{`.tow-header{display:grid;grid-template-columns:auto 1fr;gap:10px 14px;align-items:center}.tow-header-actions{justify-self:end;display:flex;align-items:center;gap:8px}.tow-nav{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.tow-nav .secondary{padding:9px 10px;border-radius:10px;background:rgba(3,13,20,.86);font-size:13px}.tow-mode{display:flex;align-items:center;border:1px solid rgba(84,223,207,.34);border-radius:999px;padding:3px;background:rgba(3,13,20,.86)}.tow-mode button{border:0;border-radius:999px;padding:7px 10px;background:transparent;color:#c8c0b6;font-weight:800;font-size:11px;letter-spacing:.05em}.tow-mode button.active{background:rgba(84,223,207,.12);color:#58dfcf;box-shadow:inset 0 0 0 1px rgba(84,223,207,.28)}@media(min-width:760px){.tow-header{grid-template-columns:auto 1fr auto}.tow-nav{grid-column:auto;display:flex;justify-self:center}.tow-header-actions{grid-column:auto}}@media(max-width:700px){.tow-header{padding:10px 12px}.tow-header .brand{min-width:0}.tow-header-actions .secondary{padding:8px 10px}.tow-dashboard-head{margin-top:4px}.tow-dashboard-head h1{font-size:28px}.tow-dashboard-head p{font-size:14px;line-height:1.45}.active-dispatch{margin-top:12px}.map-panel{margin-top:16px}}`}</style><Header logout={logout} mode={mode} setMode={setMode} onDispatch={()=>scroll('tow-dispatch')} onMap={()=>scroll('tow-case-map')} onQueue={()=>scroll('tow-queue')}/><main><section className="tow-dashboard-head"><div><span className="eyebrow">Vehicle movement</span><h1>Tow / Valet operations</h1><p>Assignment, navigation and handoff controls stay together in one driver workflow.</p></div><button className="secondary" type="button" onClick={()=>void load()}>Refresh</button></section>{error&&<div className="error">{error}</div>}
<section id="tow-dispatch" className="panel card active-dispatch"><span className="pill">ACTIVE DISPATCH</span>{active?<><h2>Dispatch {active.id.slice(0,8)}</h2><p>Case {active.case_id.slice(0,8)} · {active.transport_type}</p><div className="tow-status-strip"><span>{stageLabel[active.status]??active.status}</span>{active.eta_at&&<strong>ETA {new Date(active.eta_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</strong>}</div>{active.status==='assigned'?<div className="assignment-actions"><button type="button" className="primary" onClick={()=>void setStatus(active,'accepted')}>Accept case</button><button type="button" className="secondary decline" onClick={()=>void setStatus(active,'declined')}>Decline case</button></div>:<div className="assignment-actions"><button type="button" className="primary" onClick={()=>scroll('tow-case-map')}>Open live map</button>{next[active.status]&&<button type="button" className="secondary" onClick={()=>void setStatus(active,next[active.status])}>Mark {next[active.status].replaceAll('_',' ')}</button>}</div>}</>:<><h2>No active dispatch</h2><p>You are on standby. The live map remains available and new assignments will appear here.</p><div className="assignment-actions"><button type="button" className="primary" onClick={()=>scroll('tow-case-map')}>Open standby map</button><button type="button" className="secondary" onClick={()=>void load()}>Check assignments</button></div></>}</section>
<div id="tow-case-map"><LocalMap key={mode} caseId={active&&active.status!=='declined'?active.case_id:undefined} dispatchId={active?.id} dispatchStatus={active?.status}/></div>
<section id="tow-queue" className="tow-queue"><div className="queue-head"><div><span className="eyebrow">Dispatch queue</span><h2>{items.length?`${items.length} assignment${items.length===1?'':'s'}`:'No queued assignments'}</h2></div><button className="secondary" type="button" onClick={()=>void load()}>Refresh queue</button></div><div className="grid">{items.map(d=><button type="button" className={`card dispatch-card ${active?.id===d.id?'active':''}`} key={d.id} onClick={()=>{setSelected(d.id);scroll('tow-dispatch')}}><span className="pill">{d.transport_type} · {stageLabel[d.status]??d.status}</span><h3>Dispatch {d.id.slice(0,8)}</h3><p>Case {d.case_id.slice(0,8)}</p>{d.eta_at&&<p>ETA {new Date(d.eta_at).toLocaleString()}</p>}</button>)}</div></section></main></div>}
function Login(p:any){return <div className="shell login"><form className="panel login-card" onSubmit={p.login}><Brand/><span className="eyebrow">Tow / Valet portal</span><h1>Sign in</h1><p>Accept, navigate and update each vehicle handoff.</p><label>Email<input type="email" required autoComplete="email" value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)}/></label><label>Password<div className="password"><input type={p.show?'text':'password'} required autoComplete="current-password" value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)}/><button type="button" onClick={()=>p.setShow(!p.show)}>{p.show?'Hide':'Show'}</button></div></label>{p.error&&<div className="error">{p.error}</div>}<button className="primary wide">Enter portal</button></form></div>}
function Brand(){return <div className="brand"><span className="mark">R</span><span>ROVIQ</span></div>}
function Header({logout,onDispatch,onMap,onQueue,mode,setMode}:any){return <header className="tow-header"><Brand/><div className="tow-header-actions"><div className="tow-mode" aria-label="Map appearance"><button type="button" className={mode==='day'?'active':''} onClick={()=>setMode('day')}>☀ Day</button><button type="button" className={mode==='night'?'active':''} onClick={()=>setMode('night')}>☾ Night</button></div><button className="secondary" onClick={logout}>Sign out</button></div><nav className="tow-nav" aria-label="Tow navigation"><button className="secondary" type="button" onClick={onDispatch}>Dispatch</button><button className="secondary" type="button" onClick={onMap}>Map</button><button className="secondary" type="button" onClick={onQueue}>Queue</button></nav></header>}
