import {useEffect,useMemo,useRef,useState} from 'react';
import maplibregl from 'maplibre-gl';

type Point={lat:number;lng:number};
type LivePoint=Point&{heading:number|null;accuracy:number|null;speed:number|null};
type Spatial={origin?:unknown;current_vehicle?:unknown;destination?:unknown;transport_location?:unknown;route_context?:Record<string,unknown>};
type RouteStep={instruction?:string;type?:string;modifier?:string;name?:string;location?:number[]};
type Route={geometry?:{coordinates?:number[][]};distance?:number;duration?:number;steps?:RouteStep[]};
type Props={caseId?:string;dispatchId?:string;dispatchStatus?:string};
const BASE=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'');
const TOKEN='roviq_tow_token';
const PICKUP_STATES=new Set(['assigned','accepted','en_route','arrived']);
function auth():Record<string,string>{const t=localStorage.getItem(TOKEN);return t?{authorization:`Bearer ${t}`}:{} }
function point(value:unknown):Point|null{if(!value||typeof value!=='object')return null;const v=value as Record<string,unknown>;const lat=Number(v.lat??v.latitude),lng=Number(v.lng??v.lon??v.longitude);return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180?{lat,lng}:null}
function label(value:unknown){if(!value)return'Not available yet';if(typeof value==='string')return value;if(typeof value==='object'){const v=value as Record<string,unknown>;const s=[v.name,v.label,v.address,v.formatted_address,v.description].find(x=>typeof x==='string');if(typeof s==='string')return s;const p=point(v);if(p)return`${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}`}return'Location available'}
function rad(n:number){return n*Math.PI/180} function distanceM(a:Point,b:Point){const R=6371000,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(q)))}
function projectAhead(p:Point,heading:number|null,meters:number):Point{if(!Number.isFinite(heading)||meters<=0)return p;const R=6378137,r=Math.PI/180,lat=p.lat*r,lng=p.lng*r,b=(heading as number)*r,d=meters/R,lat2=Math.asin(Math.sin(lat)*Math.cos(d)+Math.cos(lat)*Math.sin(d)*Math.cos(b)),lng2=lng+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(lat),Math.cos(d)-Math.sin(lat)*Math.sin(lat2));return{lat:lat2/r,lng:lng2/r}}
function marker(kind:'pickup'|'destination'){const el=document.createElement('div');el.className=`rq-marker rq-dispatch-marker ${kind}`;el.innerHTML=`<span>${kind==='pickup'?'P':'D'}</span>`;return el} function puck(h:number|null){const el=document.createElement('div');el.className='rq-nav-puck';el.style.setProperty('--rq-heading',`${Number.isFinite(h)?h:0}deg`);el.innerHTML='<span></span>';return el}
function modeNow():'day'|'night'{const e=document.documentElement.dataset.roviqMode;if(e==='day'||e==='night')return e;const h=new Date().getHours();return h>=7&&h<19?'day':'night'}
function mapStyle(mode:'day'|'night'):maplibregl.StyleSpecification{return{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'background',type:'background',paint:{'background-color':mode==='night'?'#071019':'#e9e6dc'}},{id:'osm',type:'raster',source:'osm',paint:{'raster-opacity':1,'raster-saturation':mode==='night'?-0.78:-0.18,'raster-brightness-min':mode==='night'?0.06:0.78,'raster-brightness-max':mode==='night'?0.48:1,'raster-contrast':mode==='night'?0.32:0.08}}]}}
function statusText(s?:string){return String(s||'standby').replaceAll('_',' ').toUpperCase()} function stepText(r:Route|null){const s=r?.steps?.find(x=>x.instruction)||r?.steps?.[0];if(!s)return'';if(s.instruction)return s.instruction;if(s.type==='arrive')return'Arrive at destination';return s.name?`Continue on ${s.name}`:'Continue on route'}
export function LocalMap({caseId,dispatchId,dispatchStatus}:Props){const mode=useMemo(modeNow,[]),assigned=Boolean(caseId&&dispatchId);const[spatial,setSpatial]=useState<Spatial|null>(null),[live,setLive]=useState<LivePoint|null>(null),[route,setRoute]=useState<Route|null>(null),[tracking,setTracking]=useState<'starting'|'live'|'limited'>('starting'),[error,setError]=useState(''),[following,setFollowing]=useState(true);const mapNode=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),markers=useRef<maplibregl.Marker[]>([]),lastPush=useRef(0),lastRouteAt=useRef(0),lastRouted=useRef<Point|null>(null),lastTarget=useRef('');
useEffect(()=>{if(!caseId){setSpatial(null);return}let dead=false;const load=async()=>{try{const r=await fetch(`${BASE}/api/maintenance/cases/${caseId}/spatial`,{headers:auth(),cache:'no-store'});if(!r.ok)throw 0;const d=await r.json() as {spatial:Spatial};if(!dead){setSpatial(d.spatial);setError('')}}catch{if(!dead)setError('Case route context unavailable.')}};void load();const id=setInterval(()=>void load(),10000);return()=>{dead=true;clearInterval(id)}},[caseId]);
useEffect(()=>{if(!navigator.geolocation){setTracking('limited');return}const id=navigator.geolocation.watchPosition(pos=>{const p:LivePoint={lat:pos.coords.latitude,lng:pos.coords.longitude,heading:Number.isFinite(pos.coords.heading)?pos.coords.heading:null,accuracy:pos.coords.accuracy,speed:Number.isFinite(pos.coords.speed)?pos.coords.speed:null};setLive(p);setTracking('live');const now=Date.now();if(dispatchId&&now-lastPush.current>8000){lastPush.current=now;void fetch(`${BASE}/api/transport/${dispatchId}/location`,{method:'POST',headers:{'content-type':'application/json',...auth()},body:JSON.stringify({...p,capturedAt:new Date(pos.timestamp).toISOString()})}).catch(()=>{})}},()=>setTracking('limited'),{enableHighAccuracy:true,maximumAge:1000,timeout:12000});return()=>navigator.geolocation.clearWatch(id)},[dispatchId]);
function pickup(){return point(spatial?.origin)??point(spatial?.current_vehicle)} function destination(){return point(spatial?.destination)} function target(){const p=pickup(),d=destination();return dispatchStatus&&PICKUP_STATES.has(dispatchStatus)?p:(d??p)}
function drawRoute(r:Route|null){const m=mapRef.current;if(!m||!m.loaded())return;const c=r?.geometry?.coordinates??[];try{const data:any={type:'Feature',properties:{},geometry:{type:'LineString',coordinates:c}};const src=m.getSource('rq-nav-route') as maplibregl.GeoJSONSource|undefined;if(src)src.setData(data);else if(c.length)m.addSource('rq-nav-route',{type:'geojson',data});if(c.length&&!m.getLayer('rq-nav-route-casing'))m.addLayer({id:'rq-nav-route-casing',type:'line',source:'rq-nav-route',layout:{'line-join':'round','line-cap':'round'},paint:{'line-color':'#03161d','line-width':14,'line-opacity':.82}});if(c.length&&!m.getLayer('rq-nav-route-glow'))m.addLayer({id:'rq-nav-route-glow',type:'line',source:'rq-nav-route',layout:{'line-join':'round','line-cap':'round'},paint:{'line-color':'#39d9c8','line-width':9,'line-opacity':.24,'line-blur':5}});if(c.length&&!m.getLayer('rq-nav-route'))m.addLayer({id:'rq-nav-route',type:'line',source:'rq-nav-route',layout:{'line-join':'round','line-cap':'round'},paint:{'line-color':'#7ff6e7','line-width':4.5}})}catch{}}
async function requestRoute(from:Point,to:Point,force:boolean){const key=`${to.lng.toFixed(5)},${to.lat.toFixed(5)}`,moved=lastRouted.current?distanceM(from,lastRouted.current):Infinity;if(!force&&key===lastTarget.current&&Date.now()-lastRouteAt.current<10000&&moved<45)return;lastTarget.current=key;lastRouteAt.current=Date.now();lastRouted.current={...from};try{const r=await fetch(`${BASE}/api/local/route?from=${encodeURIComponent(`${from.lng},${from.lat}`)}&to=${encodeURIComponent(`${to.lng},${to.lat}`)}`,{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();if(!d?.route?.geometry?.coordinates?.length)throw 0;setRoute(d.route);setError('')}catch{setError('ROVIQ Local route temporarily unavailable.')}}
async function renderMap(force:boolean){const m=mapRef.current;if(!m||!m.loaded())return;const tow=live??point(spatial?.transport_location),p=pickup(),d=destination(),t=target();markers.current.forEach(x=>x.remove());markers.current=[];if(p)markers.current.push(new maplibregl.Marker({element:marker('pickup')}).setLngLat([p.lng,p.lat]).addTo(m));if(d)markers.current.push(new maplibregl.Marker({element:marker('destination')}).setLngLat([d.lng,d.lat]).addTo(m));if(tow)markers.current.push(new maplibregl.Marker({element:puck(live?.heading??null)}).setLngLat([tow.lng,tow.lat]).addTo(m));if(tow&&t)await requestRoute(tow,t,force);if(tow&&following){const speed=live?.speed??0,look=projectAhead(tow,live?.heading??null,Math.min(115,28+speed*3.6));m.easeTo({center:[look.lng,look.lat],zoom:Math.max(14.35,Math.min(16.35,16.15-speed*.035)),pitch:assigned?Math.max(48,Math.min(63,51+speed*.45)):28,bearing:live?.heading??m.getBearing(),duration:720,essential:true})}}
useEffect(()=>{if(!mapNode.current||mapRef.current)return;const c=live??point(spatial?.transport_location)??point(spatial?.origin)??{lat:45.5231,lng:-122.6765};const m=new maplibregl.Map({container:mapNode.current,style:mapStyle(mode),center:[c.lng,c.lat],zoom:12.8,pitch:assigned?48:18,attributionControl:{compact:true},maxZoom:19});m.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');mapRef.current=m;m.on('dragstart',()=>setFollowing(false));m.on('load',()=>{setError('');m.resize();void renderMap(true)});m.on('styledata',()=>drawRoute(route));m.on('error',e=>{const msg=String((e as any)?.error?.message??'');if(msg.includes('tile'))setError('Road map is reconnecting…')});return()=>{markers.current.forEach(x=>x.remove());m.remove();mapRef.current=null}},[]);useEffect(()=>{void renderMap(false)},[spatial,live,dispatchStatus]);useEffect(()=>drawRoute(route),[route]);
function recenter(){setFollowing(true);if(mapRef.current&&live)mapRef.current.easeTo({center:[live.lng,live.lat],zoom:assigned?15.6:14.7,pitch:assigned?56:28,bearing:live.heading??0,duration:720,essential:true})}
const distanceMiles=typeof route?.distance==='number'?route.distance/1609.344:Number(spatial?.route_context?.distanceMiles),etaMinutes=typeof route?.duration==='number'?route.duration/60:Number(spatial?.route_context?.etaMinutes),goingToPickup=Boolean(dispatchStatus&&PICKUP_STATES.has(dispatchStatus)),instruction=stepText(route)||(goingToPickup?'Proceed to pickup':'Proceed to destination');
return <section className="map-panel dispatch-context"><div className="map-head"><div><span className="eyebrow map-eyebrow">ROVIQ Local · Tow</span><h2>{assigned?(goingToPickup?'Tow → pickup':'Vehicle → destination'):'Tow live map'}</h2><p>{assigned?'Operational dispatch map: route, live tow position, pickup and destination.':'Tow standby map. GPS remains available while waiting for a dispatch.'}</p></div><span className={`live-badge ${tracking}`}>{tracking==='live'?'● GPS LIVE':tracking==='starting'?'LOCATING…':'GPS LIMITED'}</span></div><div className={`live-map-wrap rq-local-${mode}`}><div ref={mapNode} className="live-map"/><div className="rq-brand rq-tow-brand"><strong>ROVIQ</strong><span>LOCAL · TOW</span></div><div className="rq-weather rq-tow-mode"><span>{mode==='day'?'☀':'☾'}</span><span>{mode.toUpperCase()}</span></div>{assigned?<section className="rq-nav-hud rq-tow-hud"><div className="rq-nav-kicker">ROVIQ DRIVE · {statusText(dispatchStatus)}</div><div className="rq-nav-next">{instruction}</div><div className="rq-nav-meta"><strong>{Number.isFinite(etaMinutes)?`${Math.max(1,Math.round(etaMinutes))} min`:'—'}</strong><span>{Number.isFinite(distanceMiles)?`${distanceMiles.toFixed(1)} mi`:'—'}</span><span>{live?.speed!=null?`${Math.max(0,Math.round(live.speed*2.23694))} mph`:'0 mph'}</span></div></section>:<section className="rq-tow-standby"><span>TOW STANDBY</span><strong>{tracking==='live'?'Location locked · ready for dispatch':tracking==='starting'?'Acquiring tow location…':'Location limited · tap locate'}</strong></section>}<button type="button" className="rq-locate rq-map-locate" onClick={recenter}>◎</button>{error&&<div className="map-warning">{error}</div>}</div>{assigned&&<div className="spatial-grid"><div><span>Pickup</span><strong>{label(spatial?.origin??spatial?.current_vehicle)}</strong></div><div><span>Destination</span><strong>{label(spatial?.destination)}</strong></div><div><span>Tow position</span><strong>{label(live??spatial?.transport_location)}</strong></div><div><span>Dispatch status</span><strong>{statusText(dispatchStatus)}</strong></div></div>}</section>}
