import { useEffect, useRef, useState } from 'react';

type Point={lat:number;lng:number};
type LivePoint=Point&{heading:number|null;accuracy:number|null;speed:number|null};
type Spatial={case_id?:string;origin?:unknown;current_vehicle?:unknown;destination?:unknown;transport_location?:unknown;route_context?:Record<string,unknown>;updated_at?:string};
type RouteStep={type?:string;modifier?:string;name?:string;instruction?:string;location?:number[]};
type Route={geometry?:{type?:string;coordinates?:number[][]};distance?:number;duration?:number;steps?:RouteStep[]};
type RoutePayload={route?:Route};

declare global { interface Window { maplibregl?: any } }

const BASE=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'');
const TOKEN='roviq_tow_token';
const PICKUP_STATES=new Set(['assigned','accepted','en_route','arrived']);

function mapStyle(mode:'day'|'night'){
  return {
    version:8 as const,
    sources:{osm:{type:'raster' as const,tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},
    layers:[{id:'osm',type:'raster' as const,source:'osm',paint:mode==='night'?{'raster-brightness-max':.48,'raster-brightness-min':.08,'raster-contrast':.28,'raster-saturation':-.45}:{'raster-brightness-max':1,'raster-brightness-min':0,'raster-contrast':.05,'raster-saturation':-.08}}]
  };
}

function point(value:unknown):Point|null{if(!value||typeof value!=='object')return null;const v=value as Record<string,unknown>;const lat=Number(v.lat??v.latitude),lng=Number(v.lng??v.lon??v.longitude);return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180?{lat,lng}:null}
function label(value:unknown){if(!value)return'Not available yet';if(typeof value==='string')return value;if(typeof value==='object'){const v=value as Record<string,unknown>;const text=[v.name,v.label,v.address,v.formatted_address,v.description].find(x=>typeof x==='string');if(typeof text==='string')return text;const p=point(v);if(p)return`${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}`}return'Location available in case data'}
function metric(route:Record<string,unknown>|undefined,key:string){const value=route?.[key];return typeof value==='number'||typeof value==='string'?String(value):'—'}
function auth():Record<string,string>{const t=localStorage.getItem(TOKEN);return t?{authorization:`Bearer ${t}`}:{}}
function rad(v:number){return v*Math.PI/180}
function distanceM(a:Point,b:Point){const R=6371000,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(q)))}
function stepLabel(step?:RouteStep|null){if(!step)return'';if(step.instruction)return step.instruction;const dir=step.modifier?` ${step.modifier}`:'';if(step.type==='turn')return`Turn${dir}${step.name?` onto ${step.name}`:''}`;if(step.type==='depart')return`Head ${step.modifier||'forward'}${step.name?` on ${step.name}`:''}`;if(step.type==='arrive')return'You have arrived';return`${step.type||'Continue'}${dir}${step.name?` on ${step.name}`:''}`}
function nextStep(route:Route|null,current:Point|null){const steps=route?.steps??[];if(!steps.length)return null;if(!current)return steps[0];let best=steps[0],bestDistance=Infinity;for(const step of steps){if(!Array.isArray(step.location)||step.location.length<2)continue;const candidate={lng:Number(step.location[0]),lat:Number(step.location[1])};if(!Number.isFinite(candidate.lng)||!Number.isFinite(candidate.lat))continue;const d=distanceM(current,candidate);if(d<bestDistance){bestDistance=d;best=step}}return best}
function ensureMapLibre(){return new Promise<void>((resolve,reject)=>{if(window.maplibregl)return resolve();if(!document.querySelector('link[data-roviq-maplibre]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/maplibre-gl@5.23.0/dist/maplibre-gl.css';l.dataset.roviqMaplibre='1';document.head.appendChild(l)}const existing=document.querySelector('script[data-roviq-maplibre]') as HTMLScriptElement|null;if(existing){existing.addEventListener('load',()=>resolve(),{once:true});existing.addEventListener('error',()=>reject(new Error('Map failed to load')),{once:true});return}const s=document.createElement('script');s.src='https://unpkg.com/maplibre-gl@5.23.0/dist/maplibre-gl.js';s.dataset.roviqMaplibre='1';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Map failed to load'));document.head.appendChild(s)})}
function endpointMarker(kind:'pickup'|'destination'){const el=document.createElement('div');el.className=`rq-dispatch-marker ${kind}`;el.innerHTML=kind==='pickup'?'<span>P</span>':'<span>D</span>';return el}
function towPuck(heading:number|null){const el=document.createElement('div');el.className='rq-nav-puck';el.style.setProperty('--rq-heading',`${Number.isFinite(heading)?heading:0}deg`);el.innerHTML='<span></span>';return el}

export function LocalMap({caseId,dispatchId,dispatchStatus}:{caseId?:string;dispatchId?:string;dispatchStatus?:string}){
  const[spatial,setSpatial]=useState<Spatial|null>(null),[error,setError]=useState(''),[tracking,setTracking]=useState<'starting'|'live'|'limited'>('starting'),[livePoint,setLivePoint]=useState<LivePoint|null>(null),[route,setRoute]=useState<Route|null>(null),[following,setFollowing]=useState(true);
  const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),markers=useRef<any[]>([]),lastPush=useRef(0),lastRouteAt=useRef(0),lastRoutedFrom=useRef<Point|null>(null),lastTargetKey=useRef('');

  const assigned=Boolean(caseId&&dispatchId);
  useEffect(()=>{document.body.dataset.navigating=assigned?'true':'false';return()=>{delete document.body.dataset.navigating}},[assigned]);

  useEffect(()=>{if(!caseId){setSpatial(null);setError('');return}let cancelled=false;async function load(){try{const r=await fetch(`${BASE}/api/maintenance/cases/${caseId}/spatial`,{headers:auth(),cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json() as {spatial:Spatial};if(!cancelled){setSpatial(d.spatial);setError('')}}catch{if(!cancelled)setError('Case route context is not available yet.')}}void load();const timer=setInterval(()=>void load(),10000);return()=>{cancelled=true;clearInterval(timer)}},[caseId]);

  useEffect(()=>{if(!navigator.geolocation){setTracking('limited');return}const id=navigator.geolocation.watchPosition(pos=>{const p:LivePoint={lat:pos.coords.latitude,lng:pos.coords.longitude,heading:Number.isFinite(pos.coords.heading)?pos.coords.heading:null,accuracy:Number.isFinite(pos.coords.accuracy)?pos.coords.accuracy:null,speed:Number.isFinite(pos.coords.speed)?pos.coords.speed:null};setLivePoint(p);setTracking('live');const now=Date.now();if(dispatchId&&now-lastPush.current>8000){lastPush.current=now;void fetch(`${BASE}/api/transport/${dispatchId}/location`,{method:'POST',headers:{'content-type':'application/json',...auth()},body:JSON.stringify({lat:p.lat,lng:p.lng,accuracy:p.accuracy,heading:p.heading,speed:p.speed,capturedAt:new Date(pos.timestamp).toISOString()})}).catch(()=>{})}},()=>setTracking('limited'),{enableHighAccuracy:true,maximumAge:1500,timeout:10000});return()=>navigator.geolocation.clearWatch(id)},[dispatchId]);

  useEffect(()=>{let alive=true;void ensureMapLibre().then(()=>{if(!alive||!mapEl.current||mapRef.current)return;const center=livePoint??point(spatial?.transport_location)??point(spatial?.origin)??point(spatial?.destination)??{lat:45.5231,lng:-122.6765};const hour=new Date().getHours(),mode: 'day'|'night'=hour>=7&&hour<19?'day':'night';const map=new window.maplibregl.Map({container:mapEl.current,style:mapStyle(mode),center:[center.lng,center.lat],zoom:12.5,pitch:assigned?50:18,bearing:0,attributionControl:true,minZoom:3,maxZoom:18});map.addControl(new window.maplibregl.NavigationControl({showCompass:false}),'top-right');mapRef.current=map;map.on('dragstart',()=>setFollowing(false));map.on('load',()=>void renderMap(true));map.on('styledata',()=>drawRoute(route));map.on('error',(event:any)=>{const message=String(event?.error?.message??'');if(message.includes('tile')||message.includes('source'))setError('Map tiles are temporarily unavailable.')})}).catch(()=>setError('ROVIQ Local map renderer failed to load.'));return()=>{alive=false;markers.current.forEach(m=>m.remove?.());markers.current=[];mapRef.current?.remove?.();mapRef.current=null}},[]);

  useEffect(()=>{void renderMap(false)},[spatial,livePoint,dispatchStatus]);
  useEffect(()=>{drawRoute(route)},[route]);

  function pickupPoint(){return point(spatial?.origin)??point(spatial?.current_vehicle)}
  function destinationPoint(){return point(spatial?.destination)}
  function targetPoint(){const pickup=pickupPoint(),destination=destinationPoint();return dispatchStatus&&PICKUP_STATES.has(dispatchStatus)?pickup:destination??pickup}

  async function requestRoute(from:Point,to:Point,force:boolean){const targetKey=`${to.lng.toFixed(5)},${to.lat.toFixed(5)}`;const targetChanged=targetKey!==lastTargetKey.current;const moved=lastRoutedFrom.current?distanceM(from,lastRoutedFrom.current):Infinity;if(!force&&!targetChanged&&Date.now()-lastRouteAt.current<10000&&moved<45)return;lastTargetKey.current=targetKey;lastRouteAt.current=Date.now();lastRoutedFrom.current={lat:from.lat,lng:from.lng};try{const r=await fetch(`${BASE}/api/local/route?from=${encodeURIComponent(`${from.lng},${from.lat}`)}&to=${encodeURIComponent(`${to.lng},${to.lat}`)}`,{cache:'no-store'});const d=await r.json() as RoutePayload;if(!r.ok||!d.route?.geometry?.coordinates?.length)throw new Error();setRoute(d.route);setError('')}catch{setError('ROVIQ Local road route is temporarily unavailable.')}}

  function drawRoute(nextRoute:Route|null){const map=mapRef.current;if(!map||!map.loaded?.())return;const coords=nextRoute?.geometry?.coordinates??[];try{const source=map.getSource('rq-route');if(coords.length){const data={type:'Feature',properties:{},geometry:{type:'LineString',coordinates:coords}};if(source)source.setData(data);else map.addSource('rq-route',{type:'geojson',data});if(!map.getLayer('rq-route-casing'))map.addLayer({id:'rq-route-casing',type:'line',source:'rq-route',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'#03161d','line-width':14,'line-opacity':.82}});if(!map.getLayer('rq-route-glow'))map.addLayer({id:'rq-route-glow',type:'line',source:'rq-route',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'#39d9c8','line-width':9,'line-opacity':.24,'line-blur':5}});if(!map.getLayer('rq-route-core'))map.addLayer({id:'rq-route-core',type:'line',source:'rq-route',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'#7ff6e7','line-width':4.5,'line-opacity':.98}})}else if(source)source.setData({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[]}})}catch{}}

  async function renderMap(forceRoute:boolean){const map=mapRef.current;if(!map||!map.loaded?.())return;const tow=livePoint??point(spatial?.transport_location),pickup=pickupPoint(),destination=destinationPoint(),target=targetPoint();markers.current.forEach(m=>m.remove?.());markers.current=[];if(pickup)markers.current.push(new window.maplibregl.Marker({element:endpointMarker('pickup'),anchor:'center'}).setLngLat([pickup.lng,pickup.lat]).addTo(map));if(destination)markers.current.push(new window.maplibregl.Marker({element:endpointMarker('destination'),anchor:'center'}).setLngLat([destination.lng,destination.lat]).addTo(map));if(tow)markers.current.push(new window.maplibregl.Marker({element:towPuck(livePoint?.heading??null),anchor:'center',rotationAlignment:'map'}).setLngLat([tow.lng,tow.lat]).addTo(map));if(tow&&target)await requestRoute(tow,target,forceRoute);if(tow&&following){map.easeTo({center:[tow.lng,tow.lat],zoom:Math.max(map.getZoom(),15.2),pitch:assigned?50:28,bearing:livePoint?.heading??map.getBearing(),duration:550,essential:true})}else{const pts=[pickup,destination,tow].filter(Boolean) as Point[];if(pts.length>1&&forceRoute){const b=new window.maplibregl.LngLatBounds();pts.forEach(p=>b.extend([p.lng,p.lat]));map.fitBounds(b,{padding:{top:150,bottom:170,left:55,right:55},maxZoom:15,pitch:assigned?50:28,duration:700,essential:true})}else if(pts[0]&&forceRoute)map.easeTo({center:[pts[0].lng,pts[0].lat],zoom:14,pitch:assigned?50:28,duration:500,essential:true})}}

  function recenter(){setFollowing(true);const map=mapRef.current;if(!map||!livePoint)return;map.easeTo({center:[livePoint.lng,livePoint.lat],zoom:15.5,pitch:assigned?50:28,bearing:livePoint.heading??map.getBearing(),duration:500,essential:true})}

  const raw=spatial?.route_context;const distanceMiles=typeof route?.distance==='number'?route.distance/1609.344:Number(raw?.distanceMiles);const etaMinutes=typeof route?.duration==='number'?route.duration/60:Number(raw?.etaMinutes);const goingToPickup=Boolean(dispatchStatus&&PICKUP_STATES.has(dispatchStatus));const instruction=stepLabel(nextStep(route,livePoint))||(assigned?(goingToPickup?'Proceed to pickup':'Proceed to destination'):'ROVIQ Local ready');

  return <section className="map-panel dispatch-context"><div className="map-head"><div><span className="eyebrow map-eyebrow">ROVIQ Local</span><h2>{assigned?(goingToPickup?'Tow navigation · pickup':'Tow navigation · destination'):'Tow map'}</h2><p>{assigned?'Live GPS position, dispatch route and ETA powered by the ROVIQ Local routing source.':'Live road map follows the tow vehicle before a dispatch is assigned.'}</p></div><span className={`live-badge ${tracking}`}>{tracking==='live'?'● POSITION LIVE':tracking==='starting'?'LOCATING…':'LOCATION LIMITED'}</span></div><div className="live-map-wrap"><div ref={mapEl} id="map" className="live-map"/><div className="rq-map-brand"><strong>ROVIQ</strong><span>LOCAL · TOW</span></div>{assigned&&<section className="rq-nav-hud"><div className="rq-nav-scan"/><div className="rq-nav-kicker">ROVIQ DRIVE</div><div className="rq-nav-next">{instruction}</div><div className="rq-nav-meta"><strong>{Number.isFinite(etaMinutes)?`${Math.max(1,Math.round(etaMinutes))} min`:'—'}</strong><span>{Number.isFinite(distanceMiles)?`${distanceMiles.toFixed(1)} mi`:'—'}</span><span>{livePoint?.speed!=null?`${Math.max(0,Math.round(livePoint.speed*2.23694))} mph`:'0 mph'}</span></div><button type="button" className="rq-nav-follow" onClick={recenter} aria-label="Follow tow location">◎</button></section>}{!assigned&&<button type="button" className="rq-map-locate" onClick={recenter} aria-label="Center on tow location">◎</button>}{error&&<div className="map-warning">{error}</div>}</div>{assigned&&<div className="spatial-grid"><div><span>Pickup</span><strong>{label(spatial?.origin??spatial?.current_vehicle)}</strong></div><div><span>Destination</span><strong>{label(spatial?.destination)}</strong></div><div><span>Tow position</span><strong>{label(livePoint??spatial?.transport_location)}</strong></div><div><span>Current leg</span><strong>{goingToPickup?'Tow → pickup':'Vehicle → destination'}</strong></div><div><span>Distance</span><strong>{Number.isFinite(distanceMiles)?`${distanceMiles.toFixed(1)} mi`:`${metric(raw,'distanceMiles')} mi`}</strong></div><div><span>ETA</span><strong>{Number.isFinite(etaMinutes)?`${Math.max(1,Math.round(etaMinutes))} min`:`${metric(raw,'etaMinutes')} min`}</strong></div></div>}</section>
}
