import { useEffect,useState,type FormEvent } from 'react';
type Principal={role:string;actorId?:string|null}; type QueueItem={offer_id:string;case_id?:string;demand_id:string;demand_type:string;urgency:number;location?:unknown;attributes?:unknown};
const BASE=(import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/$/,''); const LOCAL_MAP=(import.meta.env.VITE_LOCAL_MAP_URL ?? 'https://roviq-local2.admytruk79.workers.dev').replace(/\/$/,''); const TOKEN='roviq_diagnostic_token'; const PRINCIPAL='roviq_diagnostic_principal';
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const token=localStorage.getItem(TOKEN);const headers:Record<string,string>={'content-type':'application/json'};if(token)headers.authorization=`Bearer ${token}`;const res=await fetch(`${BASE}${path}`,{...init,headers});if(!res.ok){const data=await res.json().catch(()=>({}));throw new Error(data.error??`request_failed_${res.status}`)}return res.json()}
export default function App(){const [principal,setPrincipal]=useState<Principal|null>(()=>{try{return JSON.parse(localStorage.getItem(PRINCIPAL)??'null')}catch{return null}});const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [queue,setQueue]=useState<QueueItem[]>([]);const [selected,setSelected]=useState<QueueItem|null>(null);const [summary,setSummary]=useState('');const [drivability,setDrivability]=useState('unknown');const [disposition,setDisposition]=useState('diagnose_only');
async function login(e:FormEvent){e.preventDefault();setError('');try{const r=await request<{accessToken:string;principal:Principal}>('/api/auth/login',{method:'POST',body:JSON.stringify({email:email.trim(),password})});if(r.principal.role!=='diagnostic')throw new Error('This account is not a diagnostic account.');localStorage.setItem(TOKEN,r.accessToken);localStorage.setItem(PRINCIPAL,JSON.stringify(r.principal));setPrincipal(r.principal)}catch(err){setError(err instanceof Error?err.message:'Unable to sign in')}}
async function load(){try{const r=await request<{queue:QueueItem[]}>('/api/diagnostics/me/queue');setQueue(r.queue)}catch(err){setError(err instanceof Error?err.message:'Unable to load queue')}} useEffect(()=>{if(principal)void load()},[principal]);
async function submitFinding(e:FormEvent){e.preventDefault();if(!selected)return;setError('');try{await request(`/api/diagnostics/demands/${selected.demand_id}/findings`,{method:'POST',body:JSON.stringify({summary,drivability,disposition})});setSummary('');setSelected(null);await load()}catch(err){setError(err instanceof Error?err.message:'Unable to save finding')}}
function logout(){localStorage.removeItem(TOKEN);localStorage.removeItem(PRINCIPAL);setPrincipal(null)}
if(!principal)return <Login title="Diagnostic portal" subtitle="Verify the issue, record findings and route the next handoff." email={email} setEmail={setEmail} password={password} setPassword={setPassword} show={show} setShow={setShow} error={error} submit={login}/>;
return <Shell title="Diagnostic" logout={logout}><div className="hero"><div><span className="eyebrow">Field verification</span><h1>Diagnostic queue</h1><p>Verify, fix in scope, or route the case onward.</p></div><div className="metric"><b>{queue.length}</b><span>active assignments</span></div></div>{error&&<div className="error">{error}</div>}<section className="local-panel"><div className="local-head"><div><span className="eyebrow">ROVIQ Local</span><h2>Live service map</h2><p>Use the shared map for your position, nearby service context and case handoffs.</p></div><a className="secondary" href={LOCAL_MAP} target="_blank" rel="noreferrer">Open full map</a></div><iframe title="ROVIQ Local map" src={LOCAL_MAP} allow="geolocation" referrerPolicy="strict-origin-when-cross-origin"/></section><div className="grid">{queue.map(item=><button key={item.offer_id} className="card" onClick={()=>setSelected(item)}><span className="pill">Urgency {item.urgency}</span><h3>{item.demand_type}</h3><p>Demand {item.demand_id.slice(0,8)}</p><strong>Record finding →</strong></button>)}</div>{selected&&<form className="panel form" onSubmit={submitFinding}><h2>Finding for {selected.demand_type}</h2><label>Summary<textarea required minLength={3} value={summary} onChange={e=>setSummary(e.target.value)}/></label><label>Drivability<select value={drivability} onChange={e=>setDrivability(e.target.value)}><option value="unknown">Unknown</option><option value="drivable">Drivable</option><option value="limited">Limited</option><option value="non_drivable">Non-drivable</option></select></label><label>Disposition<select value={disposition} onChange={e=>setDisposition(e.target.value)}><option value="diagnose_only">Diagnose only</option><option value="diagnose_and_fix">Diagnose & fix</option><option value="route_to_shop">Route to shop</option><option value="route_to_tow">Route to tow</option></select></label><div className="actions"><button className="primary">Save finding</button><button type="button" className="secondary" onClick={()=>setSelected(null)}>Cancel</button></div></form>}</Shell>}
function Login(p:any){return <div className="shell login"><form className="panel login-card" onSubmit={p.submit}><Brand/><span className="eyebrow">{p.title}</span><h1>Sign in</h1><p>{p.subtitle}</p><label>Email<input type="email" autoComplete="email" required value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)}/></label><label>Password<div className="password"><input type={p.show?'text':'password'} autoComplete="current-password" required value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)}/><button type="button" onClick={()=>p.setShow(!p.show)}>{p.show?'Hide':'Show'}</button></div></label>{p.error&&<div className="error">{p.error}</div>}<button className="primary">Enter portal</button></form></div>}
function Brand(){return <div className="brand"><span className="mark">R</span><span>ROVIQ</span></div>} function Shell({title,logout,children}:any){return <div className="shell"><header><Brand/><div><span>{title}</span><button className="secondary" onClick={logout}>Sign out</button></div></header><main>{children}</main></div>}
