import{useEffect,useMemo,useState}from'react';
const BASE=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'');const TOKEN='roviq_diagnostic_token';
type CoreCase={id:string;case_type:string;state:string;priority:string;version:number;pending_approvals:number;active_workflows:number};
type Approval={id:string;action:string;state:string;approval_type:string};type AssignmentOffer={id:string;case_id:string;case_type:string;case_state:string;priority:string;expires_at:string;reason:string|null};type Action={to:string;action:string;approvalRecommended:boolean};type Actions={version:number;transitions:Action[]};
async function req<T>(path:string,init:RequestInit={}):Promise<T>{const t=localStorage.getItem(TOKEN);const r=await fetch(`${BASE}${path}`,{...init,headers:{'content-type':'application/json',...(t?{authorization:`Bearer ${t}`}:{}),...(init.headers??{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error??`request_failed_${r.status}`)}return r.json()}
const human=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export function CoreCasePanel(){const[cases,setCases]=useState<CoreCase[]>([]),[offers,setOffers]=useState<AssignmentOffer[]>([]),[selected,setSelected]=useState<string|null>(null),[actions,setActions]=useState<Actions|null>(null),[approvals,setApprovals]=useState<Approval[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[refresh,setRefresh]=useState(0);
useEffect(()=>{let live=true;(async()=>{try{setError('');const[r,o]=await Promise.all([req<{cases:CoreCase[]}>('/api/core/me/cases'),req<{offers:AssignmentOffer[]}>('/api/core/me/assignment-offers')]);if(!live)return;setCases(r.cases);setOffers(o.offers);setSelected(cur=>cur&&r.cases.some(c=>c.id===cur)?cur:r.cases[0]?.id??null)}catch(e){if(live)setError(e instanceof Error?e.message:'Unable to load Core cases')}})();return()=>{live=false}},[refresh]);
useEffect(()=>{if(!selected){setActions(null);setApprovals([]);return}let live=true;Promise.all([req<Actions>(`/api/core/cases/${selected}/actions`),req<{approvals:Approval[]}>(`/api/core/cases/${selected}/approvals`)]).then(([a,p])=>{if(live){setActions(a);setApprovals(p.approvals)}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'Unable to load Core actions')});return()=>{live=false}},[selected,refresh]);
const c=cases.find(x=>x.id===selected)??null;const approved=useMemo(()=>new Map(approvals.filter(a=>a.state==='approved').map(a=>[a.action,a])),[approvals]);
async function respondOffer(id:string,decision:'accepted'|'declined'){setBusy(`offer:${id}`);try{setError('');await req(`/api/core/assignment-offers/${id}/respond`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({decision})});setRefresh(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Unable to respond to assignment offer')}finally{setBusy('')}}
async function move(a:Action){if(!selected||!actions)return;setBusy(a.to);try{setError('');const approval=approved.get(a.action);await req(`/api/core/cases/${selected}/transition`,{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({expectedVersion:actions.version,requestedTransition:a.to,approvalId:approval?.id,evidence:{source:'diagnostic_core_workspace'}})});setRefresh(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Unable to update Core case')}finally{setBusy('')}}
return <section className="queue-section" aria-labelledby="core-case-heading"><div className="section-head"><div><span className="eyebrow">ROVIQ Core</span><h2 id="core-case-heading">Assigned coordinated cases</h2></div><button className="secondary" onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div>{error&&<div className="error">{human(error)}</div>}{offers.length>0&&<section className="panel offer-focus"><span className="eyebrow">Assignment offers</span>{offers.map(o=><div key={o.id} style={{marginTop:10}}><h2>{human(o.case_type)} · {o.case_id.slice(0,8)}</h2><p>{human(o.priority)} priority · expires {new Date(o.expires_at).toLocaleString()}</p><div className="actions"><button className="primary" disabled={Boolean(busy)} onClick={()=>void respondOffer(o.id,'accepted')}>Accept</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void respondOffer(o.id,'declined')}>Decline</button></div></div>)}</section>}{cases.length?<div className="grid">{cases.map(x=><button key={x.id} className={`card queue-card ${selected===x.id?'active':''}`} onClick={()=>setSelected(x.id)}><span className="pill">{human(x.state)}</span><h3>{human(x.case_type)} · {x.id.slice(0,8)}</h3><p>{x.active_workflows} workflow(s) · {x.pending_approvals} approval(s)</p><strong>{selected===x.id?'Selected':'Open'} →</strong></button>)}</div>:<section className="panel empty-state"><span className="eyebrow">Core queue</span><h2>No assigned Core Cases</h2><p>Universal Cases assigned to this diagnostic actor will appear here.</p></section>}{c&&<section className="panel offer-focus"><span className="eyebrow">Selected Core Case</span><h2>Case {c.id.slice(0,8)}</h2><p>{human(c.case_type)} · {human(c.state)} · priority {human(c.priority)} · v{c.version}</p><div className="actions">{actions?.transitions.map(a=>{const ok=!a.approvalRecommended||approved.has(a.action);return <button key={a.to} className="secondary" disabled={Boolean(busy)||!ok} onClick={()=>void move(a)}>{busy===a.to?'Applying…':human(a.to)}{!ok?' · approval':''}</button>})}</div></section>}</section>}
