import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool } from '../../db/pool.js';
import { requireRole } from '../middleware/principal.js';
import { createDeadline, createServiceCase, getCaseTimeline, raiseException, transitionCase, withIdempotency } from '../../services/orchestration.js';
import { addLedgerEntry, setCustomerSnapshot, sweepExpiredDeadlines } from '../../services/operations.js';
import { loadCaseForPrincipal } from '../../services/case-access.js';
import { selectCaseActor } from '../../services/selection-authority.js';
import { assertAdminCaseScope, getAdminActorScope } from '../../services/admin-case-scope.js';
import { getExceptionQueue } from '../../services/exception-engine.js';

const createCaseBody=z.object({
 demandId:z.string().uuid().optional(),marketId:z.string().uuid().optional(),locationId:z.string().uuid().optional(),
 priority:z.enum(['low','normal','high','urgent']).optional(),drivability:z.enum(['unknown','drivable','limited','non_drivable']).optional(),
 originatingActorId:z.string().uuid().optional(),relationshipOwnerActorId:z.string().uuid().optional(),
 selectionMode:z.enum(['customer_choice','dealer_controlled','auto_dispatch','ops_override']).optional(),attributes:z.record(z.unknown()).optional()
});
const state=z.enum(['intake','triage','diagnostic_pending','diagnostic_in_progress','tow_pending','tow_in_progress','provider_selection','provider_pending','repair_in_progress','parts_pending','payment_pending','completed','cancelled']);

type TimelineEvent = { id:string; event_type:string; actor_id:string|null; occurred_at:string; payload:Record<string,unknown> };

function projectTimeline(role:string, events:TimelineEvent[]) {
  if (role==='admin') return events;
  return events
    .filter(e=>!e.event_type.startsWith('PAYOUT_'))
    .map(e=>e.event_type==='PROVIDER_SELECTED'
      ? {...e,payload:{actorId:e.payload?.actorId,selectionMode:e.payload?.selectionMode}}
      : e);
}

export async function caseRoutes(app:FastifyInstance){
 app.post('/api/maintenance/cases',{preHandler:requireRole('customer','admin')},async(req,reply)=>{const body=createCaseBody.parse(req.body);if(req.principal.role==='customer'&&(body.selectionMode==='ops_override'||body.selectionMode==='auto_dispatch'||body.selectionMode==='dealer_controlled'||body.originatingActorId||body.relationshipOwnerActorId))return reply.code(403).send({error:'case_authority_fields_admin_only'});const key=typeof req.headers['idempotency-key']==='string'?req.headers['idempotency-key']:undefined;const result=await withIdempotency(req.principal,key,'create_service_case',body,async(client)=>({status:201,body:{case:await createServiceCase(req.principal,body,client)}}));return reply.code(result.status).send(result.body);});
 app.get('/api/customers/me/cases',{preHandler:requireRole('customer')},async(req)=>{const r=await pool.query(`select c.id,c.state,c.priority,c.drivability,c.case_type,c.current_owner_role,c.recommended_actor_id,c.selected_actor_id,c.selection_mode,c.created_at,c.updated_at,c.completed_at,c.cancelled_at,s.customer_status,s.customer_message from service_cases c left join case_snapshots s on s.case_id=c.id where c.customer_actor_id=$1 order by c.created_at desc limit 200`,[req.principal.actorId]);return{cases:r.rows};});
 app.get('/api/admin/cases',{preHandler:requireRole('admin')},async(req)=>{const query=z.object({state:state.optional(),limit:z.coerce.number().int().positive().max(200).default(100)}).parse(req.query??{});const scope=await getAdminActorScope(req.principal,pool);const params:unknown[]=[];const clauses:string[]=[];if(query.state){params.push(query.state);clauses.push(`c.state=$${params.length}`);}if(scope){params.push(scope.organizationId);const org=params.length;params.push(scope.locationId);const loc=params.length;clauses.push(`exists(select 1 from service_cases sc left join actors owner on owner.id=sc.current_owner_actor_id left join actors selected on selected.id=sc.selected_actor_id left join actors recommended on recommended.id=sc.recommended_actor_id where sc.id=c.id and ((owner.organization_id=$${org} and ($${loc}::uuid is null or owner.location_id=$${loc})) or (selected.organization_id=$${org} and ($${loc}::uuid is null or selected.location_id=$${loc})) or (recommended.organization_id=$${org} and ($${loc}::uuid is null or recommended.location_id=$${loc})) or exists(select 1 from matches_offers mo join actors provider on provider.id=mo.actor_id where mo.case_id=sc.id and mo.outcome='accepted' and provider.organization_id=$${org} and ($${loc}::uuid is null or provider.location_id=$${loc}))))`);}params.push(query.limit);const where=clauses.length?`where ${clauses.join(' and ')}`:'';const r=await pool.query(`select c.* from service_cases c ${where} order by c.updated_at desc limit $${params.length}`,params);return{cases:r.rows};});
 app.get('/api/maintenance/cases/:id',async(req,reply)=>{const{id}=req.params as{id:string};try{const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});const snapshot=await pool.query('select * from case_snapshots where case_id=$1',[id]);const{has_provider_relation:_,has_transport_relation:__,has_parts_relation:___,has_mobility_relation:____,...caseProjection}=c;return{case:caseProjection,customerSnapshot:snapshot.rows[0]??null};}catch(error){if(error instanceof Error&&error.message==='forbidden')return reply.code(403).send({error:'forbidden'});throw error;}});
 app.post('/api/maintenance/cases/:id/select-provider',async(req,reply)=>{const{id}=req.params as{id:string};const body=z.object({actorId:z.string().uuid(),rationale:z.record(z.unknown()).optional()}).parse(req.body);try{const selection=await selectCaseActor(req.principal,id,body.actorId,body.rationale??{});return{selection,offer:selection.offer,case:selection.case};}catch(e){const m=e instanceof Error?e.message:'selection_failed';if(m==='case_not_found')return reply.code(404).send({error:m});if(m==='selection_forbidden')return reply.code(403).send({error:m});if(['actor_not_eligible','actor_not_serviceable','case_not_selectable','selection_already_recorded','case_demand_missing'].includes(m))return reply.code(409).send({error:m});throw e;}});
 app.get('/api/maintenance/cases/:id/transitions',async(req,reply)=>{const{id}=req.params as{id:string};try{const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});const rules=await pool.query(`select to_state,terminal from case_transition_rules where from_state=$1 and $2=any(allowed_roles)`,[c.state,req.principal.role]);const canCancel=c.state!=='completed'&&c.state!=='cancelled'&&['admin','customer'].includes(req.principal.role);const transitions=rules.rows.map(r=>({toState:r.to_state,terminal:r.terminal}));if(canCancel)transitions.push({toState:'cancelled',terminal:true});return{transitions};}catch(error){if(error instanceof Error&&error.message==='forbidden')return reply.code(403).send({error:'forbidden'});throw error;}});
 app.get('/api/maintenance/cases/:id/timeline',async(req,reply)=>{const{id}=req.params as{id:string};try{const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});return{timeline:projectTimeline(req.principal.role,await getCaseTimeline(id) as TimelineEvent[])};}catch(error){if(error instanceof Error&&error.message==='forbidden')return reply.code(403).send({error:'forbidden'});throw error;}});
 app.post('/api/maintenance/cases/:id/transition',async(req,reply)=>{const{id}=req.params as{id:string};const body=z.object({toState:state,metadata:z.record(z.unknown()).optional()}).parse(req.body);try{const c=await transitionCase(req.principal,id,body.toState,body.metadata??{});if(!c)return reply.code(404).send({error:'case_not_found'});return{case:c};}catch(e){const m=e instanceof Error?e.message:'transition_failed';if(m==='transition_forbidden'||m==='forbidden')return reply.code(403).send({error:m});if(m==='invalid_case_transition')return reply.code(409).send({error:m});throw e;}});
 app.put('/api/admin/cases/:id/customer-snapshot',{preHandler:requireRole('admin')},async(req)=>{const{id}=req.params as{id:string};await assertAdminCaseScope(req.principal,id,pool);const b=z.object({status:z.string().min(1),message:z.string().optional(),nextAction:z.string().optional(),etaAt:z.string().datetime().optional()}).parse(req.body);return{snapshot:await setCustomerSnapshot(id,b.status,b.message,b.nextAction,b.etaAt)};});
 app.post('/api/admin/cases/:id/deadlines',{preHandler:requireRole('admin')},async(req,reply)=>{const{id}=req.params as{id:string};await assertAdminCaseScope(req.principal,id,pool);const b=z.object({deadlineType:z.string().min(1),dueAt:z.string().datetime(),fallbackAction:z.string().optional(),metadata:z.record(z.unknown()).optional()}).parse(req.body);return reply.code(201).send({deadline:await createDeadline(id,b.deadlineType,b.dueAt,b.fallbackAction,b.metadata??{})});});
 app.post('/api/admin/operations/sweep-deadlines',{preHandler:requireRole('admin')},async(req)=>{const b=z.object({limit:z.number().int().positive().max(500).default(100)}).parse(req.body??{});return{processed:await sweepExpiredDeadlines(req.principal,b.limit)};});
 app.post('/api/admin/cases/:id/exceptions',{preHandler:requireRole('admin')},async(req,reply)=>{const{id}=req.params as{id:string};await assertAdminCaseScope(req.principal,id,pool);const b=z.object({code:z.string().min(1),summary:z.string().min(1),severity:z.enum(['info','warning','critical']).default('warning'),metadata:z.record(z.unknown()).optional()}).parse(req.body);return reply.code(201).send({exception:await raiseException(id,b.code,b.summary,b.severity,b.metadata??{})});});
 app.get('/api/admin/exceptions',{preHandler:requireRole('admin')},async(req)=>({exceptions:await getExceptionQueue(req.principal,{state:'open',limit:200})}));
 app.post('/api/admin/cases/:id/ledger',{preHandler:requireRole('admin')},async(req,reply)=>{const{id}=req.params as{id:string};await assertAdminCaseScope(req.principal,id,pool);const b=z.object({entryType:z.string().min(1),accountCode:z.string().min(1),counterpartyActorId:z.string().uuid().optional(),amount:z.number(),currency:z.string().length(3).default('USD'),state:z.string().default('pending'),externalReference:z.string().optional(),metadata:z.record(z.unknown()).optional()}).parse(req.body);return reply.code(201).send({entry:await addLedgerEntry({caseId:id,...b})});});
 app.get('/api/admin/cases/:id/ledger',{preHandler:requireRole('admin')},async(req)=>{const{id}=req.params as{id:string};await assertAdminCaseScope(req.principal,id,pool);const r=await pool.query('select * from ledger_entries where case_id=$1 order by occurred_at asc',[id]);return{ledger:r.rows};});
}
