import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool } from '../../db/pool.js';
import { requireRole } from '../middleware/principal.js';
import { createDeadline, createServiceCase, getCaseTimeline, raiseException, transitionCase, withIdempotency } from '../../services/orchestration.js';
import { addLedgerEntry, setCustomerSnapshot, sweepExpiredDeadlines } from '../../services/operations.js';
import { loadCaseForPrincipal } from '../../services/case-access.js';
import { selectCaseActor } from '../../services/selection-authority.js';

const createCaseBody=z.object({
 demandId:z.string().uuid().optional(),marketId:z.string().uuid().optional(),locationId:z.string().uuid().optional(),
 priority:z.enum(['low','normal','high','urgent']).optional(),drivability:z.enum(['unknown','drivable','limited','non_drivable']).optional(),
 originatingActorId:z.string().uuid().optional(),relationshipOwnerActorId:z.string().uuid().optional(),
 selectionMode:z.enum(['customer_choice','dealer_controlled','auto_dispatch','ops_override']).optional(),attributes:z.record(z.unknown()).optional()
});
const state=z.enum(['intake','triage','diagnostic_pending','diagnostic_in_progress','tow_pending','tow_in_progress','provider_selection','provider_pending','repair_in_progress','parts_pending','payment_pending','completed','cancelled']);

export async function caseRoutes(app:FastifyInstance){
 app.post('/api/maintenance/cases',{preHandler:requireRole('customer','admin')},async(req,reply)=>{const body=createCaseBody.parse(req.body);if(req.principal.role==='customer'&&(body.selectionMode==='ops_override'||body.selectionMode==='auto_dispatch'||body.originatingActorId||body.relationshipOwnerActorId))return reply.code(403).send({error:'case_authority_fields_admin_only'});const key=typeof req.headers['idempotency-key']==='string'?req.headers['idempotency-key']:undefined;const result=await withIdempotency(req.principal,key,'create_service_case',body,async(client)=>({status:201,body:{case:await createServiceCase(req.principal,body,client)}}));return reply.code(result.status).send(result.body);});
 app.get('/api/customers/me/cases',{preHandler:requireRole('customer')},async(req)=>{const r=await pool.query(`select id,state,priority,drivability,case_type,current_owner_role,recommended_actor_id,selected_actor_id,selection_mode,created_at,updated_at,completed_at,cancelled_at from service_cases where customer_actor_id=$1 order by created_at desc limit 200`,[req.principal.actorId]);return{cases:r.rows};});
 app.get('/api/admin/cases',{preHandler:requireRole('admin')},async(req)=>{const query=z.object({state:state.optional(),limit:z.coerce.number().int().positive().max(200).default(100)}).parse(req.query??{});const params:unknown[]=[];let where='';if(query.state){params.push(query.state);where=`where state=$${params.length}`;}params.push(query.limit);const r=await pool.query(`select * from service_cases ${where} order by updated_at desc limit $${params.length}`,params);return{cases:r.rows};});
 app.get('/api/maintenance/cases/:id',async(req,reply)=>{const{id}=req.params as{id:string};try{const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});const snapshot=await pool.query('select * from case_snapshots where case_id=$1',[id]);const{has_provider_relation:_,has_transport_relation:__,has_parts_relation:___,has_mobility_relation:____,...caseProjection}=c;return{case:caseProjection,customerSnapshot:snapshot.rows[0]??null};}catch(error){if(error instanceof Error&&error.message==='forbidden')return reply.code(403).send({error:'forbidden'});throw error;}});
 app.post('/api/maintenance/cases/:id/select-provider',async(req,reply)=>{const{id}=req.params as{id:string};const body=z.object({actorId:z.string().uuid(),rationale:z.record(z.unknown()).optional()}).parse(req.body);try{const selection=await selectCaseActor(req.principal,id,body.actorId,body.rationale??{});const c=await pool.query('select id,demand_id,state,selection_mode from service_cases where id=$1',[id]);const serviceCase=c.rows[0]??null;let offer=null;let updatedCase=serviceCase;if(serviceCase?.demand_id&&serviceCase.state==='provider_selection'){const existing=await pool.query(`select * from matches_offers where case_id=$1 and actor_id=$2 and outcome='offered' order by offered_at desc limit 1`,[id,body.actorId]);if(existing.rowCount){offer=existing.rows[0];}else{const created=await pool.query(`insert into matches_offers(demand_id,case_id,actor_id,rank,rule_basis) values($1,$2,$3,1,$4) returning *`,[serviceCase.demand_id,id,body.actorId,'authorized_provider_selection']);offer=created.rows[0];}updatedCase=await transitionCase(req.principal,id,'provider_pending',{offerId:offer.id,providerActorId:body.actorId,selectionMode:selection.selectionMode,source:'authorized_provider_selection'});}return{selection,offer,case:updatedCase};}catch(e){const m=e instanceof Error?e.message:'selection_failed';if(m==='case_not_found')return reply.code(404).send({error:m});if(m==='selection_forbidden'||m==='transition_forbidden')return reply.code(403).send({error:m});if(m==='actor_not_eligible'||m==='invalid_case_transition')return reply.code(409).send({error:m});throw e;}});
 app.get('/api/maintenance/cases/:id/transitions',async(req,reply)=>{const{id}=req.params as{id:string};try{const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});const rules=await pool.query(`select to_state,terminal from case_transition_rules where from_state=$1 and $2=any(allowed_roles)`,[c.state,req.principal.role]);const canCancel=c.state!=='completed'&&c.state!=='cancelled'&&['admin','customer'].includes(req.principal.role);const transitions=rules.rows.map(r=>({toState:r.to_state,terminal:r.terminal}));if(canCancel)transitions.push({toState:'cancelled',terminal:true});return{transitions};}catch(error){if(error instanceof Error&&error.message==='forbidden')return reply.code(403).send({error:'forbidden'});throw error;}});
 app.get('/api/maintenance/cases/:id/timeline',async(req,reply)=>{const{id}=req.params as{id:string};try{const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});return{timeline:await getCaseTimeline(id)};}catch(error){if(error instanceof Error&&error.message==='forbidden')return reply.code(403).send({error:'forbidden'});throw error;}});
 app.post('/api/maintenance/cases/:id/transition',async(req,reply)=>{const{id}=req.params as{id:string};const body=z.object({toState:state,metadata:z.record(z.unknown()).optional()}).parse(req.body);try{const c=await transitionCase(req.principal,id,body.toState,body.metadata??{});if(!c)return reply.code(404).send({error:'case_not_found'});return{case:c};}catch(e){const m=e instanceof Error?e.message:'transition_failed';if(m==='transition_forbidden')return reply.code(403).send({error:m});if(m==='invalid_case_transition')return reply.code(409).send({error:m});throw e;}});
 app.put('/api/admin/cases/:id/customer-snapshot',{preHandler:requireRole('admin')},async(req)=>{const{id}=req.params as{id:string};const b=z.object({status:z.string().min(1),message:z.string().optional(),nextAction:z.string().optional(),etaAt:z.string().datetime().optional()}).parse(req.body);return{snapshot:await setCustomerSnapshot(id,b.status,b.message,b.nextAction,b.etaAt)};});
 app.post('/api/admin/cases/:id/deadlines',{preHandler:requireRole('admin')},async(req,reply)=>{const{id}=req.params as{id:string};const b=z.object({deadlineType:z.string().min(1),dueAt:z.string().datetime(),fallbackAction:z.string().optional(),metadata:z.record(z.unknown()).optional()}).parse(req.body);return reply.code(201).send({deadline:await createDeadline(id,b.deadlineType,b.dueAt,b.fallbackAction,b.metadata??{})});});
 app.post('/api/admin/operations/sweep-deadlines',{preHandler:requireRole('admin')},async(req)=>{const b=z.object({limit:z.number().int().positive().max(500).default(100)}).parse(req.body??{});return{processed:await sweepExpiredDeadlines(req.principal,b.limit)};});
 app.post('/api/admin/cases/:id/exceptions',{preHandler:requireRole('admin')},async(req,reply)=>{const{id}=req.params as{id:string};const b=z.object({code:z.string().min(1),summary:z.string().min(1),severity:z.enum(['info','warning','critical']).default('warning'),metadata:z.record(z.unknown()).optional()}).parse(req.body);return reply.code(201).send({exception:await raiseException(id,b.code,b.summary,b.severity,b.metadata??{})});});
 app.get('/api/admin/exceptions',{preHandler:requireRole('admin')},async()=>{const r=await pool.query(`select e.*,c.state as case_state,c.priority from case_exceptions e join service_cases c on c.id=e.case_id where e.state='open' order by case when e.severity='critical' then 0 when e.severity='warning' then 1 else 2 end,e.created_at asc limit 200`);return{exceptions:r.rows};});
 app.post('/api/admin/cases/:id/ledger',{preHandler:requireRole('admin')},async(req,reply)=>{const{id}=req.params as{id:string};const b=z.object({entryType:z.string().min(1),accountCode:z.string().min(1),counterpartyActorId:z.string().uuid().optional(),amount:z.number(),currency:z.string().length(3).default('USD'),state:z.string().default('pending'),externalReference:z.string().optional(),metadata:z.record(z.unknown()).optional()}).parse(req.body);return reply.code(201).send({entry:await addLedgerEntry({caseId:id,...b})});});
 app.get('/api/admin/cases/:id/ledger',{preHandler:requireRole('admin')},async(req)=>{const{id}=req.params as{id:string};const r=await pool.query('select * from ledger_entries where case_id=$1 order by occurred_at asc',[id]);return{ledger:r.rows};});
}
