import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool } from '../../db/pool.js';
import { requireRole } from '../middleware/principal.js';
import { loadCaseForPrincipal } from '../../services/case-access.js';
import { audit } from '../../services/audit.js';
import { appendCaseEvent } from '../../services/orchestration.js';
import { setCustomerSnapshot } from '../../services/operations.js';

const executableRepairClass=z.enum(['battery','tire','ignition','electrical_minor','fluid_service','minor_mechanical']);
const repairClass=z.enum(['battery','tire','ignition','electrical_minor','fluid_service','minor_mechanical','unknown']);
const requiredPartSchema=z.object({sku:z.string().min(1),quantity:z.number().int().positive().default(1),partNumber:z.string().optional(),description:z.string().optional()});
const safetySchema=z.object({fireRisk:z.boolean().default(false),fuelLeak:z.boolean().default(false),highVoltageRisk:z.boolean().default(false),brakeSteeringRisk:z.boolean().default(false),unstableVehicle:z.boolean().default(false),roadsideUnsafe:z.boolean().default(false)}).default({});
const assessmentSchema=z.object({demandId:z.string().uuid().optional(),diagnosticFindingId:z.string().uuid().optional(),operatorActorId:z.string().uuid().optional(),summary:z.string().min(3),repairClass:repairClass.default('unknown'),drivability:z.enum(['drivable','limited','non_drivable','unknown']).default('unknown'),confidence:z.number().min(0).max(1).default(0.5),safety:safetySchema,requiredCapabilities:z.array(z.string().min(1)).default([]),requiredTools:z.array(z.string().min(1)).default([]),requiredParts:z.array(requiredPartSchema).default([]),estimatedMinutes:z.number().int().nonnegative().max(720).optional(),estimatedCost:z.number().nonnegative().optional(),customerAuthorizationRequired:z.boolean().default(true),evidence:z.record(z.unknown()).default({}),metadata:z.record(z.unknown()).default({})});
type Assessment=z.infer<typeof assessmentSchema>;type RequiredPart=z.infer<typeof requiredPartSchema>;
type CapabilityProfile={actor_id:string;active:boolean;repair_classes:unknown;capabilities:unknown;tools:unknown;max_estimated_minutes:number|null;max_estimated_cost:string|number|null;verified_at:string|null};
function stringArray(v:unknown):string[]{return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'):[]}
function includesAll(h:string[],n:string[]){const s=new Set(h);return n.every(v=>s.has(v))}
function operatorEligible(a:Assessment,p:CapabilityProfile|null){if(!p||!p.active||!p.verified_at)return false;if(!stringArray(p.repair_classes).includes(a.repairClass))return false;if(!includesAll(stringArray(p.capabilities),a.requiredCapabilities)||!includesAll(stringArray(p.tools),a.requiredTools))return false;if(a.estimatedMinutes!=null&&p.max_estimated_minutes!=null&&a.estimatedMinutes>p.max_estimated_minutes)return false;if(a.estimatedCost!=null&&p.max_estimated_cost!=null&&a.estimatedCost>Number(p.max_estimated_cost))return false;return true}
async function findPartsSupplier(parts:RequiredPart[]){if(!parts.length)return{available:true,supplierActorId:null as string|null};const skus=[...new Set(parts.map(p=>p.sku))];const r=await pool.query(`select supplier_actor_id,sku,sum(quantity_on_hand-quantity_reserved)::int as available from parts_inventory where active=true and sku=any($1::text[]) group by supplier_actor_id,sku`,[skus]);const bySupplier=new Map<string,Map<string,number>>();for(const row of r.rows){if(!bySupplier.has(row.supplier_actor_id))bySupplier.set(row.supplier_actor_id,new Map());bySupplier.get(row.supplier_actor_id)!.set(row.sku,Number(row.available)||0)}for(const[supplier,map]of bySupplier){if(parts.every(p=>(map.get(p.sku)??0)>=p.quantity))return{available:true,supplierActorId:supplier}}return{available:false,supplierActorId:null}}
function decide(a:Assessment,p:CapabilityProfile|null,partsAvailable:boolean){const unsafe=Object.values(a.safety).some(Boolean);if(unsafe||a.drivability==='non_drivable')return'tow_required' as const;if(a.confidence<.75||a.repairClass==='unknown')return'remote_review' as const;if(!operatorEligible(a,p))return'dispatch_field_technician' as const;if(a.requiredParts.length&&!partsAvailable)return'dispatch_field_technician' as const;return'field_repair' as const}
async function reserveDecisionParts(decision:any){const parts=(Array.isArray(decision.required_parts)?decision.required_parts:[]) as RequiredPart[];if(!parts.length)return null;const supplierActorId=decision.operator_context?.partsSupplierActorId;if(!supplierActorId)throw new Error('field_service_parts_unavailable');const client=await pool.connect();try{await client.query('begin');const reservation:any[]=[];for(const part of parts){const inv=await client.query(`select * from parts_inventory where supplier_actor_id=$1 and sku=$2 and active=true and (quantity_on_hand-quantity_reserved)>=$3 order by updated_at asc limit 1 for update`,[supplierActorId,part.sku,part.quantity]);if(!inv.rowCount)throw new Error(`field_service_parts_unavailable:${part.sku}`);await client.query('update parts_inventory set quantity_reserved=quantity_reserved+$1,updated_at=now() where id=$2',[part.quantity,inv.rows[0].id]);reservation.push({inventoryId:inv.rows[0].id,sku:part.sku,quantity:part.quantity,supplierActorId})}await client.query('commit');return reservation}catch(e){await client.query('rollback').catch(()=>{});throw e}finally{client.release()}}

export async function fieldServiceRoutes(app:FastifyInstance){
 app.get('/api/field-service/me/capabilities',{preHandler:requireRole('diagnostic','tow','partner')},async req=>{const r=await pool.query('select * from field_service_actor_capabilities where actor_id=$1',[req.principal.actorId]);return{capability:r.rows[0]??null}});
 app.put('/api/admin/field-service/actors/:actorId/capabilities',{preHandler:requireRole('admin')},async(req,reply)=>{const{actorId}=req.params as{actorId:string};const b=z.object({active:z.boolean().default(true),repairClasses:z.array(executableRepairClass).default([]),capabilities:z.array(z.string().min(1)).default([]),tools:z.array(z.string().min(1)).default([]),maxEstimatedMinutes:z.number().int().positive().max(720).nullable().optional(),maxEstimatedCost:z.number().nonnegative().nullable().optional(),metadata:z.record(z.unknown()).default({})}).parse(req.body);const actor=await pool.query("select id from actors where id=$1 and status='active'",[actorId]);if(!actor.rowCount)return reply.code(404).send({error:'actor_not_found'});const r=await pool.query(`insert into field_service_actor_capabilities(actor_id,active,repair_classes,capabilities,tools,max_estimated_minutes,max_estimated_cost,verified_by_actor_id,verified_at,metadata,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,now(),$9,now()) on conflict(actor_id) do update set active=excluded.active,repair_classes=excluded.repair_classes,capabilities=excluded.capabilities,tools=excluded.tools,max_estimated_minutes=excluded.max_estimated_minutes,max_estimated_cost=excluded.max_estimated_cost,verified_by_actor_id=excluded.verified_by_actor_id,verified_at=now(),metadata=excluded.metadata,updated_at=now() returning *`,[actorId,b.active,JSON.stringify(b.repairClasses),JSON.stringify(b.capabilities),JSON.stringify(b.tools),b.maxEstimatedMinutes??null,b.maxEstimatedCost??null,req.principal.actorId??null,JSON.stringify(b.metadata)]);await audit(req.principal,'verify_field_service_capability','actor',actorId,'field_service_capability_profile',{repairClasses:b.repairClasses,active:b.active});return{capability:r.rows[0]}});
 app.get('/api/maintenance/cases/:id/field-service',async(req,reply)=>{const{id}=req.params as{id:string};try{const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});const r=await pool.query('select * from field_service_decisions where case_id=$1 order by created_at desc',[id]);return{decisions:r.rows}}catch(e){if(e instanceof Error&&e.message==='forbidden')return reply.code(403).send({error:'forbidden'});throw e}});
 app.post('/api/maintenance/cases/:id/field-service/assess',{preHandler:requireRole('diagnostic','tow','partner','admin')},async(req,reply)=>{const{id}=req.params as{id:string};const b=assessmentSchema.parse(req.body);const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});const operatorActorId=b.operatorActorId??req.principal.actorId??null;if(req.principal.role!=='admin'&&operatorActorId!==req.principal.actorId)return reply.code(403).send({error:'operator_override_forbidden'});const profileResult=operatorActorId?await pool.query('select * from field_service_actor_capabilities where actor_id=$1',[operatorActorId]):{rows:[]};const profile=(profileResult.rows[0]??null) as CapabilityProfile|null;const parts=await findPartsSupplier(b.requiredParts);const action=decide(b,profile,parts.available);const authorizationRequired=b.customerAuthorizationRequired&&action==='field_repair';const status=authorizationRequired?'authorization_required':'proposed';const r=await pool.query(`insert into field_service_decisions(case_id,demand_id,diagnostic_finding_id,created_by_actor_id,action,status,repair_class,drivability,confidence,summary,safety_flags,required_capabilities,required_tools,required_parts,operator_context,evidence,estimated_minutes,estimated_cost,customer_authorization_required,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) returning *`,[id,b.demandId??c.demand_id??null,b.diagnosticFindingId??null,req.principal.actorId??null,action,status,b.repairClass,b.drivability,b.confidence,b.summary,JSON.stringify(b.safety),JSON.stringify(b.requiredCapabilities),JSON.stringify(b.requiredTools),JSON.stringify(b.requiredParts),JSON.stringify({operatorActorId,verifiedProfile:Boolean(profile?.verified_at),partsAvailable:parts.available,partsSupplierActorId:parts.supplierActorId,role:req.principal.role}),JSON.stringify(b.evidence),b.estimatedMinutes??null,b.estimatedCost??null,b.customerAuthorizationRequired,JSON.stringify(b.metadata)]);await appendCaseEvent(id,'FIELD_SERVICE_DECISION_PROPOSED',req.principal,{decisionId:r.rows[0].id,action,status,operatorActorId,partsAvailable:parts.available});await setCustomerSnapshot(id,'field_service_assessment',action==='tow_required'?'On-site assessment requires vehicle transport.':action==='field_repair'?'An on-site repair is available.':'The on-site assessment is being reviewed.',authorizationRequired?'Approval required':'ROVIQ is coordinating the next action');await audit(req.principal,'create_field_service_decision','service_case',id,action,{decisionId:r.rows[0].id,status,operatorActorId});return reply.code(201).send({decision:r.rows[0]})});
 app.post('/api/maintenance/cases/:id/field-service/:decisionId/authorize',{preHandler:requireRole('customer','admin')},async(req,reply)=>{const{id,decisionId}=req.params as{id:string;decisionId:string};const b=z.object({approved:z.boolean()}).parse(req.body);const c=await loadCaseForPrincipal(req.principal,id);if(!c)return reply.code(404).send({error:'case_not_found'});const existing=await pool.query('select * from field_service_decisions where id=$1 and case_id=$2',[decisionId,id]);if(!existing.rowCount)return reply.code(404).send({error:'field_service_decision_not_found'});const status=b.approved?'authorized':'declined';const r=await pool.query(`update field_service_decisions set status=$1,authorized_by_actor_id=$2,customer_authorized_at=case when $3 then now() else customer_authorized_at end,updated_at=now() where id=$4 returning *`,[status,req.principal.actorId??null,b.approved,decisionId]);await appendCaseEvent(id,b.approved?'FIELD_SERVICE_AUTHORIZED':'FIELD_SERVICE_DECLINED',req.principal,{decisionId,action:r.rows[0].action});return{decision:r.rows[0]}});
 app.post('/api/maintenance/cases/:id/field-service/:decisionId/start',{preHandler:requireRole('diagnostic','tow','partner','admin')},async(req,reply)=>{const{id,decisionId}=req.params as{id:string;decisionId:string};const d=await pool.query('select * from field_service_decisions where id=$1 and case_id=$2',[decisionId,id]);if(!d.rowCount)return reply.code(404).send({error:'field_service_decision_not_found'});const decision=d.rows[0];if(decision.customer_authorization_required&&decision.status!=='authorized')return reply.code(409).send({error:'field_service_authorization_required'});if(!['field_repair','temporary_stabilization'].includes(decision.action))return reply.code(409).send({error:'field_service_action_not_executable'});const operatorActorId=decision.operator_context?.operatorActorId??req.principal.actorId;if(req.principal.role!=='admin'&&operatorActorId!==req.principal.actorId)return reply.code(403).send({error:'field_service_operator_mismatch'});const profile=await pool.query('select active,verified_at from field_service_actor_capabilities where actor_id=$1',[operatorActorId]);if(!profile.rows[0]?.active||!profile.rows[0]?.verified_at)return reply.code(409).send({error:'field_service_operator_not_verified'});let reservation;try{reservation=await reserveDecisionParts(decision)}catch(e){return reply.code(409).send({error:e instanceof Error?e.message:'field_service_parts_unavailable'})}const r=await pool.query(`update field_service_decisions set status='in_progress',started_at=now(),metadata=metadata || $2::jsonb,updated_at=now() where id=$1 returning *`,[decisionId,JSON.stringify(reservation?{partsReservation:reservation}:{})]);await appendCaseEvent(id,'FIELD_SERVICE_STARTED',req.principal,{decisionId,action:r.rows[0].action,operatorActorId,partsReservation:reservation});return{decision:r.rows[0]}});
 app.post('/api/maintenance/cases/:id/field-service/:decisionId/complete',{preHandler:requireRole('diagnostic','tow','partner','admin')},async(req,reply)=>{const{id,decisionId}=req.params as{id:string;decisionId:string};const b=z.object({outcome:z.enum(['fixed','stabilized','failed','escalated']),notes:z.string().optional(),evidence:z.record(z.unknown()).optional()}).parse(req.body);const status=b.outcome==='failed'||b.outcome==='escalated'?'escalated':'completed';const r=await pool.query(`update field_service_decisions set status=$1,outcome=$2,completed_at=now(),evidence=evidence || $3::jsonb,metadata=metadata || $4::jsonb,updated_at=now() where id=$5 and case_id=$6 and status='in_progress' returning *`,[status,b.outcome,JSON.stringify(b.evidence??{}),JSON.stringify(b.notes?{completionNotes:b.notes}:{}),decisionId,id]);if(!r.rowCount)return reply.code(409).send({error:'field_service_not_in_progress'});await appendCaseEvent(id,'FIELD_SERVICE_COMPLETED',req.principal,{decisionId,outcome:b.outcome});await setCustomerSnapshot(id,b.outcome==='fixed'?'field_service_fixed':b.outcome==='stabilized'?'field_service_stabilized':'field_service_escalated',b.outcome==='fixed'?'Vehicle repaired on site.':b.outcome==='stabilized'?'Vehicle stabilized on site.':'On-site work could not be completed safely.',b.outcome==='fixed'?'Confirm resolution':b.outcome==='stabilized'?'Continue with approved next step':'ROVIQ will arrange towing or specialist service');return{decision:r.rows[0]}});
}
