import {useCallback,useEffect,useMemo,useState} from 'react';
import {api} from './api';

type RepairOrder={id:string;repair_order_number:string;status:string;customer_concern?:string|null;updated_at:string};
type Inspection={id:string;status:string;inspection_type:string;submitted_at?:string|null};
type Finding={id:string;severity:string;section:string;item:string};
type WorkItem={id:string;status:string;title:string;technician_actor_id?:string|null;estimated_minutes?:number|null;blocked_reason?:string|null};
type TimeEntry={id:string;work_item_id:string;started_at:string;ended_at?:string|null};
type PartRequirement={id:string;description?:string|null;part_reference?:string|null;readiness_status:string;eta?:string|null};
type Floor={repairOrder:RepairOrder;inspections:Inspection[];findings:Finding[];workItems:WorkItem[];timeEntries:TimeEntry[];summary:{inspectionCount:number;submittedInspections:number;urgentFindings:number;openWorkItems:number;activeClocks:number;laborMinutes:number}};

type WorkAction='start'|'pause'|'wait_parts'|'wait_customer'|'resume'|'qc'|'complete';

function human(value:string|null|undefined){return value?value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()):'—'}
function minutes(value:number){if(value<60)return `${value} min`;const h=Math.floor(value/60),m=value%60;return m?`${h}h ${m}m`:`${h}h`}
function eta(value:string|null|undefined){return value?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value)):'No ETA'}
function nextWorkAction(item:WorkItem):{label:string;action:WorkAction}|null{
  if(item.status==='assigned')return{label:'Start work',action:'start'};
  if(item.status==='in_progress')return{label:'Send to QC',action:'qc'};
  if(['paused','waiting_parts','waiting_customer'].includes(item.status))return{label:'Resume work',action:'resume'};
  if(item.status==='quality_control')return{label:'Complete task',action:'complete'};
  return null;
}

export function ShopOsFloorControl(){
  const[orders,setOrders]=useState<RepairOrder[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[floor,setFloor]=useState<Floor|null>(null),[parts,setParts]=useState<PartRequirement[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  const activeOrders=useMemo(()=>orders.filter(o=>!['closed','cancelled'].includes(o.status)).sort((a,b)=>new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime()),[orders]);
  const loadOrders=useCallback(async()=>{
    const response=await api.get<{repairOrders:RepairOrder[]}>('/api/shop-os/repair-orders');
    setOrders(response.repairOrders);
    setSelectedId(current=>current&&response.repairOrders.some(o=>o.id===current)?current:(response.repairOrders.find(o=>!['closed','cancelled'].includes(o.status))?.id??null));
  },[]);
  const loadFloor=useCallback(async(id:string)=>{
    const[f,p]=await Promise.all([
      api.get<Floor>(`/api/shop-os/repair-orders/${id}/floor`),
      api.get<{requirements:PartRequirement[]}>(`/api/shop-os/repair-orders/${id}/parts-requirements`)
    ]);
    setFloor(f);setParts(p.requirements??[]);
  },[]);
  useEffect(()=>{setLoading(true);setError(null);void loadOrders().catch(e=>setError(`Could not load shop floor: ${human(e instanceof Error?e.message:'request failed')}`)).finally(()=>setLoading(false))},[loadOrders]);
  useEffect(()=>{if(!selectedId){setFloor(null);setParts([]);return;}setLoading(true);setError(null);void loadFloor(selectedId).catch(e=>setError(`Could not load repair floor: ${human(e instanceof Error?e.message:'request failed')}`)).finally(()=>setLoading(false))},[selectedId,loadFloor]);
  async function refresh(){await loadOrders();if(selectedId)await loadFloor(selectedId)}
  async function workAction(item:WorkItem,action:WorkAction){setBusy(item.id);setError(null);setMessage(null);try{await api.patch(`/api/shop-os/work-items/${item.id}`,{action});setMessage(action==='qc'?'Task moved to quality check.':action==='complete'?'Task completed.':action==='resume'?'Work resumed.':'Work updated.');await refresh()}catch(e){setError(`Could not update task: ${human(e instanceof Error?e.message:'request failed')}`)}finally{setBusy(null)}}
  async function clock(item:WorkItem,clocked:boolean){setBusy(item.id);setError(null);setMessage(null);try{if(clocked)await api.post(`/api/shop-os/work-items/${item.id}/clock-out`,{endReason:'manual'});else await api.post(`/api/shop-os/work-items/${item.id}/clock-in`,{});setMessage(clocked?'Technician clock stopped.':'Technician clock started.');await refresh()}catch(e){setError(`Could not update technician time: ${human(e instanceof Error?e.message:'request failed')}`)}finally{setBusy(null)}}
  async function updatePart(part:PartRequirement,readinessStatus:'ordered'|'received'|'ready'){setBusy(part.id);setError(null);setMessage(null);try{await api.patch(`/api/shop-os/parts-requirements/${part.id}`,{readinessStatus});setMessage(readinessStatus==='ready'?'Part marked ready for installation.':readinessStatus==='received'?'Part received.':'Part marked ordered.');await refresh()}catch(e){setError(`Could not update part: ${human(e instanceof Error?e.message:'request failed')}`)}finally{setBusy(null)}}
  const activeClockIds=new Set((floor?.timeEntries??[]).filter(t=>!t.ended_at).map(t=>t.work_item_id));
  return <section className="mt-8" id="shop-os-floor-control">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="kicker">Fixed operations</p><h2 className="mt-1 text-2xl font-bold">Repair floor</h2><p className="muted mt-1 max-w-2xl text-sm">DVI, technician work, time, parts and quality control stay together on the active repair order.</p></div><button className="secondary self-start" type="button" disabled={loading} onClick={()=>void refresh()}>{loading?'Refreshing…':'Refresh floor'}</button></div>
    {message&&<div className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-100" role="status">{message}</div>}{error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-500/10 px-4 py-3 text-sm text-red-100" role="alert">{error}</div>}
    <div className="mt-5 grid gap-5 xl:grid-cols-[.42fr_.58fr]"><aside className="panel p-4"><p className="muted text-xs uppercase tracking-[.12em]">Open repair orders</p><div className="mt-3 space-y-2">{activeOrders.length===0?<p className="muted text-sm">No open repair orders.</p>:activeOrders.slice(0,20).map(order=><button key={order.id} type="button" onClick={()=>setSelectedId(order.id)} className={`w-full rounded-xl border px-3 py-3 text-left transition ${selectedId===order.id?'border-[var(--green)] bg-white/[.06]':'border-white/10 bg-white/[.02]'}`}><div className="flex items-center justify-between gap-2"><span className="font-bold">{order.repair_order_number}</span><span className="muted text-[11px]">{human(order.status)}</span></div><p className="muted mt-1 line-clamp-2 text-xs">{order.customer_concern?.trim()||'Service repair order'}</p></button>)}</div></aside>
      <div className="space-y-4">{!floor?<div className="panel p-6"><p className="font-semibold">Select a repair order</p><p className="muted mt-1 text-sm">Choose an active RO to run inspection, work and parts execution.</p></div>:<>
        <section className="panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="kicker">{floor.repairOrder.repair_order_number}</p><h3 className="mt-1 text-xl font-bold">{floor.repairOrder.customer_concern?.trim()||'Service repair order'}</h3></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-bold">{human(floor.repairOrder.status)}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-5"><div className="stat"><p className="muted text-[11px]">DVI</p><p className="mt-1 text-xl font-black">{floor.summary.submittedInspections}/{floor.summary.inspectionCount}</p></div><div className="stat"><p className="muted text-[11px]">Urgent</p><p className="mt-1 text-xl font-black">{floor.summary.urgentFindings}</p></div><div className="stat"><p className="muted text-[11px]">Open tasks</p><p className="mt-1 text-xl font-black">{floor.summary.openWorkItems}</p></div><div className="stat"><p className="muted text-[11px]">Clocked in</p><p className="mt-1 text-xl font-black">{floor.summary.activeClocks}</p></div><div className="stat"><p className="muted text-[11px]">Labor</p><p className="mt-1 text-xl font-black">{minutes(floor.summary.laborMinutes)}</p></div></div></section>
        <section className="panel p-5"><div className="flex items-center justify-between"><div><p className="kicker">Inspection</p><h3 className="mt-1 text-lg font-bold">DVI status</h3></div><span className="muted text-xs">{floor.findings.length} findings</span></div>{floor.inspections.length===0?<p className="muted mt-3 text-sm">No DVI started yet. Start the inspection from the repair-order workflow when the vehicle reaches the technician.</p>:<div className="mt-3 space-y-2">{floor.inspections.map(i=><div key={i.id} className="flex items-center justify-between gap-3 border-b border-white/10 pb-2 last:border-0"><div><p className="font-semibold">{human(i.inspection_type)} inspection</p><p className="muted text-xs">{floor.findings.filter(f=>f.id&&f.severity==='urgent').length} urgent findings across this RO</p></div><span className="text-xs font-bold">{human(i.status)}</span></div>)}</div>}</section>
        <section className="panel p-5"><div className="flex items-center justify-between"><div><p className="kicker">Technician work</p><h3 className="mt-1 text-lg font-bold">Work in progress</h3></div><span className="muted text-xs">{floor.workItems.length} tasks</span></div><div className="mt-3 space-y-3">{floor.workItems.length===0?<p className="muted text-sm">No work items created yet.</p>:floor.workItems.map(item=>{const next=nextWorkAction(item),clocked=activeClockIds.has(item.id);return <article key={item.id} className="rounded-xl border border-white/10 bg-white/[.02] p-3"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-bold">{item.title}</span><span className="muted text-[11px]">{human(item.status)}</span></div>{item.blocked_reason&&<p className="mt-1 text-xs text-amber-200">Blocked: {item.blocked_reason}</p>}{item.estimated_minutes!=null&&<p className="muted mt-1 text-xs">Estimate {minutes(item.estimated_minutes)}</p>}</div><div className="flex flex-wrap gap-2">{next&&<button className="primary" type="button" disabled={busy===item.id} onClick={()=>void workAction(item,next.action)}>{busy===item.id?'Updating…':next.label}</button>}{['assigned','in_progress','paused'].includes(item.status)&&<button className="secondary" type="button" disabled={busy===item.id} onClick={()=>void clock(item,clocked)}>{clocked?'Clock out':'Clock in'}</button>}{item.status==='in_progress'&&<><button className="secondary" type="button" disabled={busy===item.id} onClick={()=>void workAction(item,'wait_parts')}>Wait for parts</button><button className="secondary" type="button" disabled={busy===item.id} onClick={()=>void workAction(item,'wait_customer')}>Wait for customer</button></>}</div></div></article>})}</div></section>
        <section className="panel p-5"><div className="flex items-center justify-between"><div><p className="kicker">Parts</p><h3 className="mt-1 text-lg font-bold">Readiness</h3></div><span className="muted text-xs">{parts.length} requirements</span></div><div className="mt-3 space-y-3">{parts.length===0?<p className="muted text-sm">No parts requirements on this repair order.</p>:parts.map(part=><article key={part.id} className="rounded-xl border border-white/10 bg-white/[.02] p-3"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="font-bold">{part.description?.trim()||part.part_reference||'Required part'}</p><p className="muted mt-1 text-xs">{human(part.readiness_status)} · {eta(part.eta)}</p></div><div className="flex flex-wrap gap-2">{['identified','sourcing'].includes(part.readiness_status)&&<button className="secondary" type="button" disabled={busy===part.id} onClick={()=>void updatePart(part,'ordered')}>Mark ordered</button>}{['ordered','eta_known'].includes(part.readiness_status)&&<button className="secondary" type="button" disabled={busy===part.id} onClick={()=>void updatePart(part,'received')}>Mark received</button>}{part.readiness_status==='received'&&<button className="primary" type="button" disabled={busy===part.id} onClick={()=>void updatePart(part,'ready')}>Ready to install</button>}</div></div></article>)}</div></section>
      </>}</div></div>
  </section>
}
